### ISSUE TITLE
Setup integration test framework and write a simple integration test

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#1]
- [ ] Using https://github.com/cosmos/cosmos-sdk/tree/develop/cmd/gaia/cli_test as an example create a `cmd/integration_test` folder for Regen Ledger, pull out all the `gaia` specific stuff and get it setup for `xrnd`, `xrncli`, and a Postgres index
- [x] Create a `make integration_test` command
- [ ] Create two accounts with some `xrn`
- [ ] Test sending money from one account to another using `xrncli` and verify that the balances are correct
- [ ] Verify that the send transaction and its block are indexed correctly in Postgres
- [ ] Test creating and retrieving a `geo` shape with `xrncli`
- [ ] Verify that the created shape can also be retrieved from the `geo` table in Postgres
- [ ] Add an integration test stage to GitLab CI with a Postgres docker service
- [ ] Update the README to reflect any difference from how Cosmos does things

**Comment by clevinson** [comment]
@aaronc should this get closed ?
