### ISSUE TITLE
Use Gov Handler for custom credit type proposals

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#1005]
## Summary 

The ClassInfo data model previously had the credit type embedded in the structure. This was changed during the recent upgrades to have ClassInfo only contain the abbreviation under the impression that we would upgrade to v0.46 and use gov messages for param changes. 

## Proposal

~~Upon credit class creation, we should fetch the requested credit type from x/params, and then save that structure in the credit type ORM table. This gives us a few benefits:~~

Create a gov handler for proposing new credit types. The handler should verify the credit type structure and store it in the ORM.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
Credit types shouldn't really be in params at all IMHO but just in the orm table. We should just have a gov handler (since 0.46 isn't ready)

**Comment by ryanchristo** [comment]
> Credit types shouldn't really be in params at all IMHO but just in the orm table. We should just have a gov handler (since 0.46 isn't ready)

Can you elaborate on the gov handler and how credit types would be added without them being a param?

**Comment by aaronc** [comment]
> > Credit types shouldn't really be in params at all IMHO but just in the orm table. We should just have a gov handler (since 0.46 isn't ready)
> 
> Can you elaborate on the gov handler and how credit types would be added without them being a param?

See how x/upgrade does it:
- https://github.com/cosmos/cosmos-sdk/blob/master/x/upgrade/handler.go
- https://github.com/cosmos/cosmos-sdk/blob/4f1cc3aeac7884cf1f522b87af04a455e92db7cf/simapp/app.go#L310
