### ISSUE TITLE
Simple Send Credit CLI Command

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#1023]
## Summary

The current CLI cmd for Sending credits works, but is a bit cumbersome for users who may just want to execute a simpler transaction (sending tradable credits from 1 account to another). 

## Proposal

We should make a CLI comand for simple credit transfers. We could call this something like `send-single` or `simple-send` or call this `send` and rename the existing one to `send-batch`

it could work like so:

### Send tradable
```
regen tx ecocredit send-simple 45.2351 C01-20200101-20220101-001 regen1zz22dfpvw3zqpeyhvhmx944a588fgcal3u7ss3
```
### Send retired
```
regen tx ecocredit send-simple 45.2351 C01-20200101-20220101-001 regen1zz22dfpvw3zqpeyhvhmx944a588fgcal3u7ss3  --retire-to="SOME-LOCATION"
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
I think this would be a nice addition but `send-simple` is not very descriptive and `send-batch` might be confusing since this is in relation to credits that are issued in batches.

**Comment by ryanchristo** [comment]
I think this would be a nice addition but `send-simple` is not very descriptive and `send-batch` might be confusing since this is in relation to credits that are issued in batches. I think `send` and `send-batch` would be ok though.
