### ISSUE TITLE
Register resolver based on url not id

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1024]
## Summary

Currently we register data to a resolver by passing the resolver id alongside the data. When a resolver is defined, we register the resolver using a unique url. A user is more likely to know the resolver url than the resolver id.

## Problem Definition

The resolver id holds no meaning to the user. In order to register data to a resolver, the user will need to first query the resolver by resolver url to get the resolver id.

## Proposal

Update `RegisterResolver` to take a resolver url rather than a resolver id.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
This is intended as an optimization to allow for registering lots of data with URLs without necessarily creating a lot of additional state in the block history. That's the same reason we don't allow anchoring data with IRIs but rather with data structures which should be more terse. We don't need to stick with that necessarily but that's the logic at least. It assumes data being registered at a massive scale will benefit from such optimizations

**Comment by ryanchristo** [comment]
> registering lots of data with URLs

I'm not sure I follow. We register data with resolver id at the moment, not the url. The proposed change would be to register data with a url, which shouldn't affect state.

```
// MsgRegisterResolver is the Msg/RegisterResolver request type.
message MsgRegisterResolver {
  // manager is the address of the resolver manager who registered this
  // resolver with Msg/DefinedResolver.
  string manager = 1;

  // resolver_id is the ID of a resolver defined with Msg/DefineResolver.
  uint64 resolver_id = 2;

  // content_hashes is a list of content hashes which the resolver claims to
  // serve.
  repeated ContentHash content_hashes = 3;
}
```

Would become:

```
// MsgRegisterResolver is the Msg/RegisterResolver request type.
message MsgRegisterResolver {
  // manager is the address of the resolver manager who registered this
  // resolver with Msg/DefinedResolver.
  string manager = 1;

  // resolver_id is the ID of a resolver defined with Msg/DefineResolver.
  string resolver_url = 2;

  // content_hashes is a list of content hashes which the resolver claims to
  // serve.
  repeated ContentHash content_hashes = 3;
}
```

**Comment by aaronc** [comment]
Yeah but it's still more bytes

**Comment by ryanchristo** [comment]
Ok, maybe better to leave as is then.

**Comment by aaronc** [comment]
I'd even advocate for making some methods use the content database id instead of the hash if it makes sense
