### ISSUE TITLE
Remove Info suffix from ecocredit state proto messages

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1029]
## Summary

In order to create human-readable query responses for the ecocredit module (#1022), we need to create a new proto message for each query response (i.e. we are currently using state proto messages that represent addresses as bytes and that include identifiers only meant to be used internally).

The state messages already use the `Info` suffix, which seems like a potentially fitting suffix to add to the query proto messages that include human-readable information about the item queried. Also, the removal of the `Info` suffix from the state proto messages has been requested for other reasons (see https://github.com/regen-network/regen-ledger/pull/1004#discussion_r846608439).

## Problem Definition

The `Info` suffix is being used for state proto messages that include information that is not human-readable.

## Proposal

Rename `ClassInfo`, `ProjectInfo`, and `BatchInfo` to `Class`, `Project`, and `Batch`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
Sounds good to me 👍
