### ISSUE TITLE
Add key to CreditType for efficient lookups

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1030]
## Summary

`CreditType` currently uses a string as the primary key (i.e. `abbreviation`) and `ClassInfo` and `ClassSequence` currently use this primary key to link to a `CreditType` (i.e. `credit_type_abbrev`).

For efficient lookups, we should use an auto-incrementing `key` as the primary key and update state proto messages that link to a credit type to use `credit_type_key` (or `type_key`) rather than `credit_type_abbrev`.

See #1021 for reference on how `key` is being used as the primary key and to link tables.
 
## Problem Definition

Using `abbreviation` as the primary key is not efficient nor consistent with how we are linking tables.

## Proposal

Add a `uint64 key` field to `CreditType` and update linked tables using `credit_type_abbrev` to use `credit_type_key`. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
Currently a single character abbreviation takes less storage space than the smallest compressed `uint64` which is 2 bytes. Only a 3 character abbreviation would benefit and that's just 1 byte. I think it's an optimization that's not needed given abbrev is limited to 1-3 bytes
