### ISSUE TITLE
Update batch_denom to denom within BatchInfo

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1031]
## Summary

We currently reference the denom of a batch as `batch_denom` within `BatchInfo`. This is redundant and this field could simply be `denom`, which is also consistent with how we reference the id for a credit class and the id for a project as `id` within `ClassInfo` and `ProjectInfo` (pending #1021).

## Problem Definition

A `batch_` prefix is unnecessary within `BatchInfo` and is inconsistent with how we reference identifiers within other state proto messages. This also produces code such as `BatchDenom: batch.BatchDenom` within `BatchInfo`.

## Proposal

Remove `batch_` prefix within `BatchInfo` and update accordingly.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
+1. more in line with `Coin` as well which simply specifies `denom` in the struct, not `coin_denom` 😄

**Comment by aaronc** [comment]
+1
