### ISSUE TITLE
Remove unnecessary fields from events

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1035]
## Summary

Events should return only the necessary information that can then be used to lookup relevant details (e.g. creating a project should emit an event that includes the project id so that the project information can be looked up using the id rather than the event including all the project information).

## Problem Definition

Events are not intended to be used in place of queries and should only include the necessary information to look up more information with queries.

## Proposal

Remove unnecessary fields from events.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
👍
