### ISSUE TITLE
Remove project and retirement prefix from jurisdiction

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1036]
## Summary

As a followup to #1020, we should reconsider when we use `project_` and `retirement_` with `jurisdiction`. We should also reconsider event fields but this should be evaluated for all events separately (#1035).

## Problem Definition

Redundant use of `project_` and `retirement_` when referencing `jurisdiction` within certain objects.

## Proposal

I think it would be safe to change the following:

- `ProjectInfo` should  use `jurisdiction` rather than `project_jurisdiction`.
- `MsgCreateProject` should use `jurisdiction` rather than `project_jurisdiction`.

I think it would be safe to remove the following  (#1035):

- `EventCreateProject` should not include `project_jurisdiction`.
- `EventCreateBatch` should not include `project_jurisdiction`.

~I'm not sure about the following:~

- ~`MsgTake` could be `jurisdiction` rather than `retirement_jurisdiction` (i.e. the jurisdiction in which the credits are taken and retired if retire-on-take is true).~
- ~`MsgBuyDirect` could be `jurisdiction` rather than `retirement_jurisdiction` (i.e. the jurisdiction in which the credits are purchased and retired if retire-on-take is true).~

~I'm less sure about the following:~

- ~`BatchIssuance` could be `jurisdiction` rather than `retirement_jurisdiction` if the documentation is clear but this might also cause more confusion.~
- ~`SendCredits` could be `jurisdiction` rather than `retirement_jurisdiction` if the documentation is clear but this might also cause more confusion.~

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
So jurisdiction can be used for both project origination and retirement which are two very different things. I think we should prefix with `project_` or `retirement_` in any context where their could be some confusion and not prefix otherwise. I'd probably leave MsgTake, MsgBuyDirect, Issuance and SendCredits alone and shorten the other cases
