### ISSUE TITLE
Create Launch Repo for Regen Mainnet

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#105]
- [ ] Script for creating genesis file (from csv)
- [ ] Launch instructions & seed nodes

**Comment by aaronc** [comment]
Created this https://github.com/regen-network/mainnet. I've assigned myself to #212

**Comment by aaronc** [comment]
Can you help with the launch instructions and seed nodes @anilCSE ?

**Comment by anilCSE** [comment]
Sure @aaronc
