### ISSUE TITLE
Docs for regen cli commands are returning 404s

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-ledger#1083]
## Summary of Bug

The links for docs on each cli command are returning 404s.

## Steps to Reproduce

Go to https://docs.regen.network/COMMANDS and click on any of the links.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Thanks for reporting. The links work for me when navigating to the commands from main page but there seems to be an issue when accessing the pages via direct link. For example, I can go to https://docs.regen.network/commands and click a command to see the documentation for that command but I cannot go directly to https://docs.regen.network/commands/regen.

Related to #1058

**Comment by wgwz** [comment]
@ryanchristo it’s possible that when i was seeing the 404’s i caught the system in temporary state where they were unavailable. next time i’ll include screenshots. this looks good to me now.
