### ISSUE TITLE
generated protos have broken syntax

### ISSUE THREAD

**Issue by pyramation** [regen-network/regen-ledger#1126]
## Summary of Bug

`regen/ecocredit/orderbook/v1alpha1/memory.proto` has broken syntax here https://github.com/regen-network/regen-ledger/blob/master/proto/regen/ecocredit/orderbook/v1alpha1/memory.proto#L31-L43

## Version

latest

## Steps to Reproduce

if you try to parse the proto files with a parser, like protobufjs, the syntax of this proto will cause errors.

## Attempted fixes

I was able to get things to parse with these changes https://github.com/pyramation/protobufs/commit/e2b30fff2324216c99f9d4b95d6f4ad7c01839e5 

You'll notice another unrelated change, `cosmos/orm/v1alpha1/orm.proto` => `cosmos/orm/v1/orm.proto` as in the latest v1alpha1 is not there.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by blushi** [comment]
cc/ @clevinson @ryanchristo @technicallyty @aaronc

**Comment by ryanchristo** [comment]
@pyramation Thanks for opening an issue. The orderbook is still in development and will not be included in the next release but we should fix the syntax. We have not migrated to the latest orm version but we should do that as well. I'll take a look today.
