### ISSUE TITLE
Reassess need for `contract` as a field in MsgBridge() & MsgBridgeReceive()

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#1127]
> One thing that came up in discussion with @ryanchristo today is that we may actually want to revise our thinking around "contract" being an explicit field in the `Bridge()` API call...
> 
> This was my oversight when writing out #1084... From a security perspective, we can't only rely on an end user's desired "contract" for tokens to get minted into on the destination chain. As this may not actually be the corresponding TCO2 contract for the given batch denom.  Since the bridge service will anyway need to manage their own mapping between batch denoms & TCO2 contracts on the destination chain, there probably isn't much added value in the user providing this upfront...

_Originally posted by @clevinson in https://github.com/regen-network/regen-ledger/pull/1101#pullrequestreview-983975547_

@aaronc do you have thoughts on this as you're pretty close to the bridge work?

**Comment by aaronc** [comment]
I don't have a strong opinion. You guys might know more than me. Maybe we should also ask Toucan?

**Comment by clevinson** [comment]
Following up here with some comments I had previously made in #1206.

From conversations we've had both at regen + with Toucan folks, it seems that we've reached alignment on adding a `contract` field into the `MsgBridgeReceive()` call so that regen ledger will store on-chain a mapping between ecocredit batches and Toucan contract addresses on polygon.

This indeed does mean that we can remove the `contract` field from the `MsgBridge()` call, as there's no need for an end user on the Regen side to state the destination contract address on Polygon, as this will be inferred from the on-chain mapping in regen ledger.

Some outstanding questions still remain though...

### Inconsistent contract addresses for a given project vintage

While I understand it's intended that project vintages on Polygon correspond 1-1 with TCO2 contract addresses, we still need to decide on how we handle the unlikely edge case of a `MsgBridgeRecieve()` with the same project vintage metadata, but a different contract address than has been previously used.

Example would look like:
- Alice bridges 500 credits to regen ledger from Polygon. The credits come from contract address `0xA` which represents project Foo, 2015 vintage on Verra.
- This creates a new ecocredit batch on regen ledger corresponding to project Foo, 2015 vintage, and it stores the Polygon contract address for this vintage as `0xA`.
- Bob later bridges 200 credits to regen ledger from Polygon. These credits come from a contract address `0xB` which has metadata corresponding to the same project Foo and 2015 vintage.

2 options for how we handle Bob's `MsgBridgeReceive()`:
1.  **error out**: Don't allow Bob to bridge his credits, as Project Foo / 2015 Vintage can only have credits bridged from contract `0xA` since that was the first contract linked with this set of metadata
2. **create a new batch**: Treat bob's bridge request as valid, and simply create a new batch on regen ledger corresponding to contract `0xB`.3. 

### Contract <> Batch Mapping

In either case above, it remains true that we want to have a 1-1 mapping btw contract address on polygon and ecocredit batch on regen.  To support that, @ryanchristo and I were discussing a potential upgrade to the `MsgBridgeReceive()` logic to make it more straightforward when determining whether to create a new batch or dynamically mint to a pre-existing batch.

#### Proposed logic

- Given a project and vintage data has not been bridged before
- When a user calls `MsgBridgeReceive()` with a the vintage data above and a contract address
- Then the vintage data is used to create a new project + batch, and the contract address is stored in the contract <> batch mapping
- When a user calls `MsgBridgeReceive()` with the same vintage data and contract address above (a subsequent time)
- Then the contract address is recognized and the corresponding batch is immediately minted into

Another way of phrasing this is - When processing `MsgBridgeReceive()` the first check should be if the contract address has a corresponding batch in Regen Ledger's mapping table. If a mapping exists, we know exactly which batch to mint to. If a mapping does not exist, we use the project + vintage data to instantiate a new batch (and project if necessary), and the store the contract <> batch mapping In the mapping table.

### Handling of changing metadata

One last edge case which we'll need to consider is how we handle hte potential for updated metadata on the Toucan side. Since metadata cannot update for a credit batch on regen ledger, then if we choose the "contract address" as the main lookup for batches (as described above), we'll avoid any issues for handling updating metadata.

If however, we still were using project metadata as a primary lookup for determining whether a corresponding batch existed on regen ledger, then we could get into all sorts of problems when the project metadata updates.

@ryanchristo and I, in speaking about this yesterday, both thought that prioritizing the contract <> batch mapping as the main lookup mechanism for new batches will get rid of any problems that may arise from metadata mutability on the toucan side.

**Comment by dave** [comment]
Yup I kinda agree, the Batch really should be looked up by contract instead of metadata...
