### ISSUE TITLE
Update ORM to Latest Version 

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#1136]
After https://github.com/cosmos/cosmos-sdk/issues/11980 is merged, we should revert https://github.com/regen-network/regen-ledger/pull/1115 and update ORM to the latest version. This will require some additional changes as some function signatures have changed https://github.com/cosmos/cosmos-sdk/issues/11655.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Updating to the latest will also resolve #1113

**Comment by ryanchristo** [comment]
Closed via #1344 #1368 #1369 #1381 #1383
