### ISSUE TITLE
Genesis vaildation fails for mainnet export

### ISSUE THREAD

**Issue by kaustubhkapatral** [regen-network/regen-ledger#1169]
## Summary of Bug

Running `regen validate-genesis` on the current mainnet export returns the following errors:
```
regen validate-genesis
Error: error validating genesis file /root/.regen/config/genesis.json: name field cannot be blank
Usage:
  regen validate-genesis [file] [flags]

Flags:
  -h, --help   help for validate-genesis

Global Flags:
      --home string         directory for config and data (default "/root/.regen")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```

```
regen validate-genesis
Error: error validating genesis file /root/.regen/config/genesis.json: symbol field cannot be blank
Usage:
  regen validate-genesis [file] [flags]

Flags:
  -h, --help   help for validate-genesis

Global Flags:
      --home string         directory for config and data (default "/root/.regen")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors

```
## Version

v3.0.0

## Steps to Reproduce

Take a state export from a mainnet node using the following command `regen export --height <current-height> --for-zero-height > export.json`. Replace the original `genesis.json` with `export.json` and execute `regen validate-genesis`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kaustubhkapatral** [comment]
The empty fields mentioned in the errors relates to denom metadata. If the field are manually filled in then it passes validation check.

**Comment by ryanchristo** [comment]
I think this might be related to how we set denom metadata when creating a basket token. Will have a look.

**Comment by aleem1314** [comment]
> I think this might be related to how we set denom metadata when creating a basket token. Will have a look.

We don't have baskets on the mainnet. Looks like we didn't set `name` and `symbol` fields for `uregen` denom.
