### ISSUE TITLE
Balance/Denom credit design

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#117]
## Summary

This proposes an architecture for ecosystem service credits (#107) based on the existing Cosmos SDK `x/bank` and `x/ibc/applications/transfer` `Coin` model.

## Problem Definition

See #107 

## Proposal

*This is based off of work done in https://github.com/regen-network/reDAOmint/tree/reDAOmint/x/ecocredit and updated to actually use an updated `x/bank` under the hood.*

In [ADR 001](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-001-coin-source-tracing.md) a convention for modules defining a "namespace" of denom identifiers is outlined.

We define a denom identifier for a credit batch as: `fmt.Sprintf("ecs/%s/%s", classId, batchId)` where `classId` are `batchId` unique string identifiers for the credit class and batch.

The `ecs` (ecosystem-service credit) module, defines the following `Msg`s for creating credit classes and batches, and retiring credits:

```proto
service Msg {
  rpc CreateClass(MsgCreateClass) returns (MsgCreateClassResponse);
  rpc CreateBatch(MsgCreateBatch) returns (MsgCreateBatchResponse);
  rpc Retire(MsgRetire) returns (MsgRetireResponse);
}

message MsgCreateClass {
  string designer;
  repeated string issuers;
  bytes metadata;
}

message MsgCreateClassResponse {
  string class_id;
}

message MsgCreateBatch {
  string issuer;
  string class_id;
  repeated BatchIssuance issuance;
}

message MsgCreateBatchResponse {
  string batch_denom;
}

message BatchIssuance {
  string recipient;
  string tradeable_units;
  string retired_units;
}

message MsgRetire {
  string holder;
  repeated cosmos.base.Coin credits;
}

message MsgRetireResponse { } 
```

### Pros
* integrates smoothly with existing Cosmos paradigm (`sdk.Coin`, `x/bank` and IBC transfer)

### Cons
* requires upgrades to `x/bank` to be performant (https://github.com/cosmos/cosmos-sdk/issues/7092) and elegant (https://github.com/cosmos/cosmos-sdk/issues/7093 and https://github.com/cosmos/cosmos-sdk/issues/7113).

### Neutral
* the `ecs` module will need to track balances of retired/burned coins

**Comment by robert-zaremba** [comment]
I didn't go through all details of the `x/bank` changes you propose, but instead of extending it, how about creating a new module which will extend it? With that we will keep `x/bank` minimal.

**Comment by robert-zaremba** [comment]
This new module could do things like: checked transfers / whitelisting, compliance etc...

**Comment by aaronc** [comment]
Some of the changes I'm suggesting to `x/bank` are relatively minor or should be done anyone. The ocaps stuff allows better encapsulation so other module can manage more rules based stuff like transfers/whitelisting on top of bank. I agree `x/bank` should be minimal.

**Comment by robert-zaremba** [comment]
It seams that https://github.com/regen-network/regen-ledger/pull/125 supersedes this issue, and it will be easier to keep discussion in one place. Shall we remove this issue , and other references to this issue (to keep focus in one place)? You can add _Consequences_ section to a README file or to a PR description.
