### ISSUE TITLE
ecocredit: return better errors for class/batch.. not found

### ISSUE THREAD

**Issue by aleem1314** [regen-network/regen-ledger#1171]
## Summary

Most of the queries in ecocredit module simply return `not found` error. It is hard to debug when we have multiple ORM getters.

## Version

master

## Proposal

Return better error message for class/batch... not found.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
I can address this in #1160
