### ISSUE TITLE
Cli doc

### ISSUE THREAD

**Issue by kaustubhkapatral** [regen-network/regen-ledger#1222]
## Summary of Bug

 - Example for `regen tx ecocredit sell` has this `regen tx ecocredit sell "[{batch_denom: "C01-20210101-20210201-001", quantity: "5", ask_price: "100regen", disable_auto_retire: false}]"`
 Format of batch denom is incorrect. Batch denom now  also includes project_id. A valid batch denom should look something like this `C01-002-20210101-20250101-001`

 - If the above example is used to submit a sell order, we get the following error `regen is not allowed to be used in sell orders: invalid request`. The example should have `ask_price: "100uregen",`

 - Example for `regen tx ecocredit buy-direct-batch` has this as the contents of a json file
 ```
		[
			{
			   "sell_order_id": 52,
			   "quantity": "32.5",
			   "bid_price": {"denom": "uregen", "amount": "32000000"},
			   "disable_auto_retire": false,
			   "retirement_jurisdiction": "US-NY"
			},
		]
```
This json file fails validation due to a comma before the end of the array.

## Version
`v4.0.0-beta1`

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Resolved in #1199
