### ISSUE TITLE
Use custom address prefix within feature files / unit tests

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1243]
## Summary

The account address prefix `regen` is initialized at runtime and therefore the default `cosmos` account address prefix is used within our unit tests. Given we are writing feature files that act as a specification for the intended behavior of Regen Ledger features, it would be nice to use `regen` within our unit tests. ~It does not look like this is possible with the current version of the sdk.~

The following can be added to base suite setup for unit tests:

```
	cfg := sdk.GetConfig()
	cfg.SetBech32PrefixForAccount("regen", "regenpub")
```

## Problem Definition

The use of the `cosmos` prefix does not accurately reflect the expected behavior of Regen Ledger features.
 
## Proposal

Configure base suite setup for unit tests to use custom `regen` prefix and update address values as needed.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Might make more sense to just do this once within an `init` function in the root of each module. Maybe add a `config.go` file with the `init` function that includes the two lines mentioned above.

**Comment by wgwz** [comment]
hey @ryanchristo  i'm interested in working on this one!

**Comment by wgwz** [comment]
@ryanchristo made a naive attempt in the PR above, but i need some guidance to learn how to run the tests correctly. didn't actually check that my changes are working, just was aiming to get sorta close on it.

**Comment by ryanchristo** [comment]
> hey @ryanchristo i'm interested in working on this one!

Great! I've assigned you.

> @ryanchristo made a naive attempt in the PR above, but i need some guidance to learn how to run the tests correctly. didn't actually check that my changes are working, just was aiming to get sorta close on it.

Left a comment in the pull request: https://github.com/regen-network/regen-ledger/pull/1253#issuecomment-1179637647
