### ISSUE TITLE
Genesis validation check is failing on redwood export

### ISSUE THREAD

**Issue by kaustubhkapatral** [regen-network/regen-ledger#1249]
## Summary of Bug
`regen validate-genesis` is failing when a genesis is created with a state export of redwood testnet.
```
root@96425-redwood-test-1:~# regen validate-genesis
Error: error validating genesis file /root/.regen/config/genesis.json: metadata's first denomination unit must be the one with base denom 'eco.uC.NCT'
```
It does not affect the operation of the chain and doesn't seem to be critical in nature.

## Version
`release/v3.0.x`

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Thanks for opening this. This issue will be fixed with the state migrations but unfortunately there's no way to fix this on redwood without a migration so we can probably close this once redwood has been upgraded.

**Comment by ryanchristo** [comment]
Thanks for opening this. This issue will be fixed with the state migrations but unfortunately there's no way to fix this on redwood without a migration so we should be able to close this once redwood has been upgraded.

**Comment by ryanchristo** [comment]
@kaustubhkapatral can you check that validate genesis does not fail after the migration with the temporary testnet?

**Comment by ryanchristo** [comment]
@kaustubhkapatral can you double check this does not fail after the migration for both redwood and mainnet?

**Comment by ryanchristo** [comment]
I tested mainnet and redwood export and validate genesis after state migrations and received no issues with mainnet but received the following error when validating the genesis file from exported redwood state:

`Error: error validating genesis file /home/ryan/.regen/config/genesis.json: unknown credit batch 0 in basket`

**Comment by ryanchristo** [comment]
cc @aleem1314 @kaustubhkapatral

**Comment by ryanchristo** [comment]
I'm guessing the error above is fixed assuming bank validation happens before ecocredit validation but looks like there is a new issue related to basket state within the exported ecocredit state.

**Comment by kaustubhkapatral** [comment]
@ryanchristo For me the `export` command itself is failing on redwood export after migration

```
root@96425-redwood-test-1:~# regen export --height 1550 --for-zero-height > new-export.json
9:50AM INF asserting crisis invariants inv=0/13 module=x/crisis name=ecocredit/batch-supply
panic: invariant broken: not found
        CRITICAL please submit the following transaction:
                 tx crisis invariant-broken ecocredit batch-supply

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/crisis/keeper.Keeper.AssertInvariants({{0xc000159180, 0xd, 0x10}, {{0x283b330, 0xc0000fc8a0}, 0xc0000101e0, {0x2815f50, 0xc0000fc9a0}, {0x2815fa0, 0xc0000fca30}, ...}, ...}, ...)  
        /root/go/pkg/mod/github.com/regen-network/cosmos-sdk@v0.45.0-regen-1/x/crisis/keeper/keeper.go:83 +0x677
github.com/regen-network/regen-ledger/v4/app.(*RegenApp).prepForZeroHeightGenesis(_, {{0x282e3d8, 0xc0000501f0}, {0x283d0e0, 0xc0024c1680}, {{0x0, 0x0}, {0x0, 0x0}, 0x60e, ...}, ...}, ...)
        /root/go/src/github.com/regen-ledger/app/export.go:89 +0x178
github.com/regen-network/regen-ledger/v4/app.(*RegenApp).ExportAppStateAndValidators(0xc000d23000, 0x1, {0x39509e8, 0x0, 0x0})
        /root/go/src/github.com/regen-ledger/app/export.go:32 +0x178
github.com/regen-network/regen-ledger/v4/app/regen/cmd.createRegenappAndExport({0x282f210, 0xc001110600}, {0x283c808, 0xc0000101d0}, {0x0, 0x0}, 0x60e, 0x0?, {0x39509e8, 0x0, ...}, ...)
        /root/go/src/github.com/regen-ledger/app/regen/cmd/root.go:303 +0x44f
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc000e2a000?, {0xc000ff14a0?, 0x0?, 0x3?})
        /root/go/pkg/mod/github.com/regen-network/cosmos-sdk@v0.45.0-regen-1/server/export.go:71 +0x31c
github.com/spf13/cobra.(*Command).execute(0xc000e2a000, {0xc000ff1440, 0x3, 0x3})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d7680)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/regen-network/regen-ledger/v4/app/regen/cmd.Execute(0xc0000021a0?)
        /root/go/src/github.com/regen-ledger/app/regen/cmd/root.go:141 +0x1eb
main.main()
        /root/go/src/github.com/regen-ledger/app/regen/main.go:12 +0x1e

```

**Comment by ryanchristo** [comment]
#1284 resolves the export after upgrade issue on redwood for me. @kaustubhkapatral can you double check?

**Comment by kaustubhkapatral** [comment]
I can confirm that the binary built from `master` branch fixes the state export and genesis validation issue on a fresh redwood state export.

**Comment by ryanchristo** [comment]
I'm going to close this as the only remaining issue is what we are solving with the migrations. I've double checked the metadata is in the current order on redwood (which would throw an error with genesis validation after upgrading) and double checked it exists in the exported state after the migration: https://hackmd.io/thM1B-NLTbu-qXWYsQyC-A?both
