### ISSUE TITLE
Improve command examples and consistent format

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1271]
## Summary

Tracking issue for minor inconsistencies and areas where we could improve naming, examples, and descriptions:

- `q ecocredit types` should be `q ecocredit credit-types`
- `q ecocredit balance` should be `q ecocredit batch-balance` ?
- `q ecocredit supply` should be `q ecocredit batch-supply` ?
- `tx ecocredit create-class` example should use full issuer address
- `tx ecocredit create-class` example should use IRI for metadata
- `tx ecocredit create-class` example should use default fee amount or mainnet fee amount for fee
- `tx ecocredit create-project` example should use real jurisdiction for jurisdiction
- `tx ecocredit create-project` example should use IRI for metadata
- `tx ecocredit create-project` example should use verra project id for reference id
- `tx ecocredit create-batch` example should use full timestamp (error with example)
- `tx ecocredit create-batch` example should use IRI for metadata
- `tx ecocredit create-batch` example does not include `open` (and should it include `origin_tx`?)
- `tx ecocredit sell` example should use valid batch denom (using old format without project id)
- `tx ecocredit sell` example should use full timestamp (error with example)
- `tx ecocredit sell` example should use json struct for ask price (error with example)
- `tx ecocredit retire` example should use valid batch denom (using old format without project id)
- `tx ecocredit cancel` example should use valid batch denom (using old format without project id)
- `tx ecocredit send` example has batch denom and recipient in the wrong positions
- `tx ecocredit update-sell-orders` example should use keys with the `new_` prefix (error with example)
- `tx ecocredit update-sell-orders` example should use json struct for new ask price (error with example)
- `tx ecocredit create-basket` example should use real values in example (name, credit type, class)
- `tx ecocredit create-basket` example should use default fee amount or mainnet fee amount for fee
- `tx ecocredit create-basket` credit type flag should be consistent with field name (i.e. credit type abbrev)
- `tx ecocredit create-basket` basket fee flag should be consistent with field name (i.e. fee) ?
- `tx ecocredit take-from-basket` example should use `=` for `retire-on-take` (error with example)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aleem1314** [comment]
> * `q ecocredit types` should be `q ecocredit credit-types`
> * `q ecocredit balance` should be `q ecocredit batch-balance` ?
> * `q ecocredit supply` should be `q ecocredit batch-supply` ?

+1
