### ISSUE TITLE
Groups Module on Chain

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#128]
Update groups module to stargate and merge into Regen Ledger (wiring up with app.go, etc.)

**Comment by aaronc** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | State
----- | --------- | --------- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Upgrade groups module to Stargate #72](https://github.com/regen-network/cosmos-modules/issues/72) | N/A | blushi | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by clevinson** [comment]
Closing in favor of #378 -- Zenhub issue for tracking Groups module work.
