### ISSUE TITLE
Regen Ledger DevNet

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#129]
Set up persistent dev net infrastructure, and corresponding forks of integrations to allow users to easily get faucet tokens, send transactions, and play around with Regen Ledger functionality using a live network.

**Comment by aaronc** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | State
----- | --------- | --------- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Setup big dipper / block explorer for devnet #139](https://github.com/regen-network/regen-ledger/issues/139) | Open Climate Collabathon | anilCSE | Open


###### do-not-edit-end-codetree-epic-issues
