### ISSUE TITLE
[x/data]: Wire up with app.go & add integration tests

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#132]
Wire up x/data module with app.go and add integration tests.

**Comment by amaurymartiny** [comment]
app.go is already wired up in https://github.com/regen-network/regen-ledger/pull/118

**Comment by clevinson** [comment]
Great. Integration tests i think should be lower priority. More important stuff for the collabathon is documentation, getting all CLI & API methods up and running, and possibly some swagger docs :)
