### ISSUE TITLE
Update ibc-go from v2 to v5

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1327]
## Summary

The next version of ibc-go that supports cosmos-sdk v0.46 will be ibc-go v5.0. There is a [tracking issue](https://github.com/cosmos/ibc-go/issues/1800) and [milestone](https://github.com/cosmos/ibc-go/milestone/33) for v5.0. We will be migrating from ibc-go v2.0, so we will need to follow the migration guide for each release since v2.0:

- https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v2-to-v3.md
- https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v3-to-v4.md
- [update link once available ] https://github.com/cosmos/ibc-go/pull/1826

Adding interchain accounts and the migrations to support interchain accounts can be addressed separately (#1328).

Follow-up

* [x] bump IBC version to stable release(v5.0)
* [x] Adding support for IBC [fee](https://github.com/cosmos/ibc-go/tree/v5.0.0-beta1/modules/apps/29-fee) module (relayer incentive mechanism) @technicallyty
* [x] controller module @technicallyty 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
we should ensure we are upgrading to `v5.0.1` as v5.0.0 contains a security vuln. upgrade guides here: https://github.com/cosmos/ibc-go/releases/tag/v5.0.1

**Comment by ryanchristo** [comment]
Fee module and controller module added and updated to v5.0.1. Closing this issue.
