### ISSUE TITLE
[x/ecocredit]: Add CLI commands

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#133]
Create cli commands for ecocredit module functionality (both tx and query functionality, mirroring MsgServer and QueryServers)

**Comment by clevinson** [comment]
Are there more CLI commands planned to be added to this? Seems like only `create credit_class` exists so far?

**Comment by robert-zaremba** [comment]
Last week I finished on adding all query commands and `create credit_class`. @aaronc was coding yesterday - helped with interface registration and some other cleanups. So, I will add other commands tomorrow.
