### ISSUE TITLE
add-genesis-account not using configured keyring-backend

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1345]
## Summary of Bug

The `add-genesis-account` command is defined within each application. If keying backend is set using `regen config`, it should be possible to run the `add-genesis-account` command without explicitly setting the `--keyring-backend` flag.

## Version

`v4.0.0`

## Steps to Reproduce

```
regen init validator --chain-id test
regen config keyring-backend test
regen keys add test
regen add-genesis-account test 1000000000stake
```

Receive the following error:

```
Error: failed to get address from Keybase: validator.info: key not found [regen-network/cosmos-sdk@v0.45.0-regen-1/crypto/keyring/keyring.go:465]
```

Run with the flag and no error:

```
regen add-genesis-account test 1000000000stake --keyring-backend test
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
i'm unable to repro this, was this fixed?

**Comment by ryanchristo** [comment]
Huh. It wasn't working 12 days ago. Maybe I was using the wrong branch or maybe this was resolved with recent changes. I just tested again and seems like it's working as expected.
