### ISSUE TITLE
Add CosmWasm module to regen ledger

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#137]

**Comment by robert-zaremba** [comment]
Lets start with sharing info here and in chat about Stargate support

**Comment by clevinson** [comment]
Is this actaully done? I see that the module was merged... but from what I gather by conversations w/ the CosmWasm team is that there still isn't CosmWasm <> Stargate compatibility. So what does it mean that we merged in this module?

**Comment by anilCSE** [comment]
@clevinson yes, there's no release tagged for `stargate` on Cosmwasm but they have a working branch. We are using latest commit hash from there. We can update the dependencies to use a tagged version when they have a release
