### ISSUE TITLE
Bump mainnet sdk version to v0.45.7

### ISSUE THREAD

**Issue by anilCSE** [regen-network/regen-ledger#1396]
## Summary

v0.45.7 has a number of non-state breaking changes which are not part of current mainnet release. Update the mainnet release sdk version to v0.45.7

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Completed with 4.1.4
