### ISSUE TITLE
Manual testing IBC integration and test network relayers

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1458]
## Summary

In the next release, we will be including the interchain account host module (and potentially the controller module). We also make use of IBC denominations in the marketplace as part of the allowed denoms functionality.

We should have a relayer or multiple relayers set up between test networks so that we can manually test IBC functionality. We should also have some way to easily spin up a local testing environment with a relayer between two chains.

## Problem Definition

A simple setup process for testing IBC integration between two local test networks would enable us to do more thorough testing. Our stable test network (Redwood) is incomplete without the ability to test IBC functionality.

## Proposal

- [ ] Set up at least one relayer between Redwood and another stable test network (@dpdanpittman)
- [x] Create a script and supporting documentation to spin up a local testing envirnoment with a relayer between two chains
  - https://github.com/aleem1314/ica-testing (@aleem1314)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
we can use this to test ICA https://github.com/cosmos/interchain-accounts-demo

**Comment by ryanchristo** [comment]
Testing scripts have been created and tests have been run:

https://github.com/aleem1314/ica-testing
https://hackmd.io/L4Ru-CeuQZ6VMMrBXYDHLA?view
https://github.com/choraio/testing
https://hackmd.io/xfkQsLDHRVat8nLqtpsbOw?view

The only thing left is setting up a(nother) relayer between redwood and another testnet. We discussed this in a recent network ops call, so maybe not necessary to track here. @dpdanpittman feel free to close if so.

**Comment by ryanchristo** [comment]
We have multiple relayers set up for redwood now and we are tracking in the network ops board. Closing.
