### ISSUE TITLE
ecocredit: update sell orders returns an error if new quantity is zero

### ISSUE THREAD

**Issue by aleem1314** [regen-network/regen-ledger#1472]
## Summary of Bug

The `UpdateSellOrders` txn returns an error if new quantity is set to zero. As per the proto docs user can cancel sell order by setting `new_quantity` to zero.

https://github.com/regen-network/regen-ledger/blob/cad5068c1eabf2daa71c3a6a7ee2c5f35240e80a/proto/regen/ecocredit/marketplace/v1/tx.proto#L103-L105
## Version

`v4.0` and `main`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Aha! Good catch. I think it would be easier and make more sense to just update the proto comment. We already have a separate method for cancelling a sell order and this comment was likely written before we implemented.
