### ISSUE TITLE
Setup Swagger Docs

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#161]
Swagger UI docs should be generated from grpc-gateway endpoints. Ideally these should also be publicly accessible on a known node (e.g. the persistent peer documented [here](https://github.com/regen-network/testnets#regen-devnet-1)).

**Comment by amaurymartiny** [comment]
We should also first add grpc-gateway endpoints to proto files.

**Comment by clevinson** [comment]
nice catch @amaurymartiny. Just made an issue for that.

Swagger seems already enabled on master with all of the standard SDK endpoints (see here: http://devnet.regen.network:1317/swagger/)

When tackling the rest of this issue, we hsould also cleanup the metadata on this
- drop usage of "Gaia" in swagger docs
- rename "Cosmos SDK - Legacy REST and gRPC Gateway docs - hey" to "Regen Ledger REST API"

**Comment by amaurym** [comment]
blocked on #182
