### ISSUE TITLE
App prefixed environment variable not working as expected

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1651]
## Summary of Bug

Using the app prefixed environment variable is not working as expected. Adding `REGEN_` and the name of a flag seems to work for some commands but not entirely.

For example, using `REGEN_HOME` when initializing a node creates the home directory set by the environment variable but it also creates a home directory in the default location and then deleting the home directory and attempting to initialize the node again, an error is returned saying the genesis file already exists.

I have not tested this further but we should investigate whether this is only an issue with initializing a node and whether this is working as expected with some flags and not others. cc @paul121 feel free to add any additional comments.

## Version

`main` / `v5.0.0-beta1` / `v5.0.0-rc1`

## Steps to Reproduce

```
REGEN_HOME=test ./build/regen init test
```

Note that the home directory is created in both the location specified by the environment variable and the default location. This is expected but the genesis file should only be in the specified location and the default location should not include the initialized genesis file - the default location will always include the configuration settings for running the binary.

Delete the specified home directory and run the command again.

```
REGEN_HOME=test ./build/regen init test
```

Receive the following error:

```
Error: genesis.json file already exists: /home/ryan/.regen/config/genesis.json
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dpdanpittman** [comment]
I was able to duplicate this error and will investigate.  As mentioned above, when setting REGEN_HOME to test and initializing the chain, the regen binary creates the test home directory but also tries to create the default directory at ~/.regen.

**Comment by clevinson** [comment]
Think this is related to this PR on the SDK: https://github.com/cosmos/cosmos-sdk/pull/9040/files#diff-146f73b0327c426deb3126e44f9234c7a6fe190c1bcb4c98ab8366b3485922ed

Reading the comment it says:
```
		WithViper("") // In simapp, we don't use any prefix for env variables.
```

So likely we just need to update the corresponding line on our side:

https://github.com/regen-network/regen-ledger/blob/750875c3025ea8916defe4451145b2860eb87c26/app/client/cli/root.go#L57

@dpdanpittman do you think you could take a crack at this in a PR and test it locally?

**Comment by ryanchristo** [comment]
@dpdanpittman you can use the `EnvPrefix` constant in `app.go` for this rather than writing it out.

**Comment by dpdanpittman** [comment]
> Think this is related to this PR on the SDK: https://github.com/cosmos/cosmos-sdk/pull/9040/files#diff-146f73b0327c426deb3126e44f9234c7a6fe190c1bcb4c98ab8366b3485922ed
> 
> Reading the comment it says:
> 
> ```go
> 		WithViper("") // In simapp, we don't use any prefix for env variables.
> ```
> 
> So likely we just need to update the corresponding line on our side:
> 
> https://github.com/regen-network/regen-ledger/blob/750875c3025ea8916defe4451145b2860eb87c26/app/client/cli/root.go#L57
> 
> @dpdanpittman do you think you could take a crack at this in a PR and test it locally?

Updating  
```go
		WithViper("")
 ``` 
 to 
 ```go
		WithViper("app.EnvPrefix")
 ``` 
in https://github.com/regen-network/regen-ledger/blob/750875c3025ea8916defe4451145b2860eb87c26/app/client/cli/root.go#L57 yields the same result.  If default directory already exists the `REGEN_HOME` flag does not create a new directory and throws the following error. `Error: genesis.json file already exists: /home/qwoyn/.regen/config/genesis.json`

**Comment by ryanchristo** [comment]
`app.EnvPrefix` should not be a string (i.e. it should not be in quotes).

**Comment by dpdanpittman** [comment]
Oops, not sure where those quotes came from.  Removed quotes but no change.  `REGEN_HOME` yields the same result as before.

**Comment by dpdanpittman** [comment]
I tested `HOME=test-home-regen ./build/regen init test-home-regen` and it gave me the expected result.  Other commands such as `REGEN_CHAIN_ID=testing-1 ~/regen-ledger/build/regen init test-1` work fine however.  Will continue to investigate but hopefully this is helpful for now @paul121

**Comment by paul121** [comment]
Thanks @dpdanpittman! Good to know there is a workaround using `HOME`... although my understanding is that `HOME` is likely used for other programs as well so I might be careful using that.

For now... :D

```
$ alias redwood="regen --home /redwood"
$ redwood
```

**Comment by dpdanpittman** [comment]
Good call.  Your workaround works well too! Ill keep digging.
