### ISSUE TITLE
amino signing for gov deposit transactions fails

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#1717]
> Did manual testing for Amino for `group` and `gov` messages. I am able to successfully execute `group` messages. 
> I am getting following error for `gov` messages
> 
> ```
> "Error when broadcasting tx 194AED34FB434451732E1B3AB869EA42CC004C1631625F3E281CC25A831BC03E at height 0. Code: 4; Raw log: signature verification failed; please verify account number (8), sequence (2) and chain-id (testnet): unauthorized"
> ```
> 
> Here is the sample repo to test amino signing https://github.com/aleem1314/group-gov-amino-testing

_Originally posted by @aleem1314 in https://github.com/regen-network/regen-ledger/issues/1456#issuecomment-1371066846_

**Comment by clevinson** [comment]
@ryanchristo and I have both reproduced the issue.

@ryanchristo using the repo above (and this hackMD: https://hackmd.io/Q-iN8S0sS-afyRpt8np6Xg)

I reproduced using the CLI (and attempting to manually inspect the sign bytes on my ledger device).  See below:

```sh
$ regen tx gov deposit 1 5000uregen --fees 5000uregen --from ledger_test
# Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
# {"body":{"messages":[{"@type":"/cosmos.gov.v1.MsgDeposit","proposal_id":"1","depositor":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd","amount":[{"denom":"uregen","amount":"5000"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uregen","amount":"5000"}],"gas_limit":"200000","payer":"","granter":""},"tip":null},"signatures":[]}
# confirm transaction before signing and broadcasting [y/N]: y
# Error: JSON Contains whitespace in the corpus
```

**Comment by ryanchristo** [comment]
Not sure what's going on with your attempt but I was able to successfully submit a deposit via the cli using a ledger device.

```
./build/regen tx gov deposit 1 5000uregen --fees 5000uregen --from ledger_test
```

```
  total_deposit:
  - amount: "5000"
    denom: uregen
```

**Comment by ryanchristo** [comment]
Maybe `regen` needed to be `./build/regen` and you were using another version...?

**Comment by ryanchristo** [comment]
This leaves me thinking that either there is an issue in Keplr with the new gov messages or in the testing repository.

**Comment by ryanchristo** [comment]
One thing I noticed is that the gov module is the only module that registers amino messages using a version in the name:

```
	legacy.RegisterAminoMsg(cdc, &MsgDeposit{}, "cosmos-sdk/v1/MsgDeposit")
```

I also noticed the group module has inconsistent amino message names (some with `/group` and some without):

```
	legacy.RegisterAminoMsg(cdc, &MsgCreateGroup{}, "cosmos-sdk/MsgCreateGroup")
	legacy.RegisterAminoMsg(cdc, &MsgLeaveGroup{}, "cosmos-sdk/group/MsgLeaveGroup")
```

I updated the test repository to test `MsgLeaveGroup` and received the same error using `MsgLeaveGroup`.

**Comment by ryanchristo** [comment]
cc @clevinson here's a fork with `MsgLeaveGroup`: https://github.com/ryanchristo/group-gov-amino-testing

**Comment by ryanchristo** [comment]
Here's a working version of `MsgLeaveGroup`: https://github.com/ryanchristo/group-gov-amino-testing/commit/a5d2164c236e2bb72680accc2902b52181196049

**Comment by clevinson** [comment]
So I'm not sure why my CLI tx's were failing above, but they seem to be working now.  So let's ignore my previous bug report involving "Error: JSON Contains whitespace in the corpus".

To further debug, I put some `fmt.PrintF`'s in the regen ledger amino verification pathway, and was able to verify the difference btw what @aleem1314's repo generates, and what the server expects.

AminoConverter generates:
`{"chain_id":"regen-sandbox","account_number":"11","sequence":"3","fee":{"amount":[{"amount":"2600000","denom":"uregen"}],"gas":"260000"},"msgs":[{"type":"cosmos-sdk/v1/MsgDeposit","value":{"amount":[{"denom":"uregen","amount":"1000"}],"depositor":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd","proposal_id":1}}],"memo":""}`

Server expects:
`{"account_number":"11","chain_id":"regen-sandbox","fee":{"amount":[{"amount":"5000","denom":"uregen"}],"gas":"200000"},"memo":"","msgs":[{"type":"cosmos-sdk/v1/MsgDeposit","value":{"amount":[{"amount":"5000","denom":"uregen"}],"depositor":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd","proposal_id":"2"}}],"sequence":"3"}`

The main difference causing the issue is that the `proposal_id` needs to be converted to a string in the [MsgDeposit AminoConverter](https://github.com/aleem1314/group-gov-amino-testing/blob/master/src/types/gov/amino.ts#L67).

I can't find exactly where there is amino converter documentation explaining this, but I was able to verify that in regen-js, we similarly convert fields to string if they are defined as  `uint64` in the proto files (see [here](https://github.com/regen-network/regen-js/blob/main/packages/api/src/tx/modules/ecocredit/marketplace/v1/buy_direct_amino.ts#L43)).


If the above hypothesis is correct, then it seems the bug is actually just a mis-implementation of the amino converters in @aleem1314's [testing repo](https://github.com/aleem1314/group-gov-amino-testing).

**Comment by aleem1314** [comment]
> @aleem1314 can you confirm that you think this resolves the issue? Were there other amino tests that were failing besides group/MsgDeposit that aren't explained by the `uint64` => `string` conversion?

Yes. Converting `proposalId` to string fixes the issue. Both `Deposit` and `Vote` messages working with ledger.
