### ISSUE TITLE
Using cid.Bytes() for storing the CID in proto messages causes poor UX across gRPCurl and CLI

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#174]
When writing the gRPC tutorial (using grpcurl), I walked through an example of querying an example CID, after anchoring and signing it from the CLI.

The CID i used for anchoring and signing over the CLI is: `zb2rhe5P4gXftAwvA4eXQ5HJwsER2owDyS9sKaQRRVQPn93bA`.

Whenever the CLI is handling CID's from the user, the corresponding CLI commands run something like:

```go
cid, err := gocid.Decode(args[1])
if err != nil {
	return err
}

msg := data.MsgAnchorDataRequest{
	Sender: clientCtx.GetFromAddress().String(),
	Cid:    cid.Bytes(),
}
```

The issue here is that `cid.Bytes()` represents the raw bytes, excluding the multibase prefix at the beginning of the CID string (`z` in our case above). What's stored on-chain is the raw bytes of the base encoded string portion of the CID as shown below:
`<multibase-type-code><base-encoded-string>`

This may be all fine if we can expect gRPC users to have the same understanding of "CID bytes", but one case where this definitely feels like poor DevX is when interacting with gRPCurl (or presumably gRPC Gateway), as both of these services enforce base64 encoding of bytes.

So to successfully query the same CID that I had set above, I had to strip the multibase prefix (`z`), lookup the multibase code (`base58btc`), decode the remaining base encoded bytes from `base58btc`, and then re-encode them as base64.

Now i know we would probably expect users to be using some kind of CID library for most of this stuff, which probably would have a `.Bytes()` method to do the conversion i describe... but "playing around with the command-line", this seems like a pretty bad UX.

I'd appreciate others thoughts on what the best solution here is. I would normally lean towards changing CIDs to be encoded as strings instead of bytes in proto messages. I imagine the most natural encoding for users to senda CID  across a REST endpoint is going to be the full string encoding (including multibase prefix), not some funky base64 version of the underlying decoded bytes.

However, I feel like that goes against some of what CID is meant to be - an identifier for content. If you have two different multibase encodings of the same CID bytes, those are treated as the same CID in the current implementation. Changing the wire encoding to bhe stirngs instead of bytes would change this behavior - where two people could have two different CID's of the same data (just using different multibase encodings) and they would be treated as different CIDs onchain....

**Comment by clevinson** [comment]
Further evidence of inconsistent behavior:

When sending a transaction via the CLI, the JSON preview it gives of the transaction (as well as the `TxResponse`, which contains JSON encoded events) both have the base64 encoded, non multibase prefixed CID:
```
build ; ./regen tx data sign $MY_ADDRESS $EXAMPLE_CID --node http://18.220.101.192:26657 --chain-id regen-devnet-1
{"body":{"messages":[{"@type":"/regen.data.v1alpha1.Msg/SignData","signers":["regen:1qx9tsl46vkgf9tf8pl3chm7mkmqa5s30ydjdzx"],"cid":"AVUSIG5v95UKNhh6gBYTQm6Fjc5obNfX48D8Qu4DMActJFyV"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"30191","txhash":"D267F1B0E4FBAD2D96BA8C66F680C09928CEA9B4FC64515B614BEC8537A4D309","codespace":"","code":0,"data":"0A230A212F726567656E2E646174612E7631616C706861312E4D73672F5369676E44617461","raw_log":"[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/regen.data.v1alpha1.Msg/SignData\"}]},{\"type\":\"regen.data.v1alpha1.EventSignData\",\"attributes\":[{\"key\":\"cid\",\"value\":\"\\\"AVUSIG5v95UKNhh6gBYTQm6Fjc5obNfX48D8Qu4DMActJFyV\\\"\"},{\"key\":\"signers\",\"value\":\"[\\\"regen:1qx9tsl46vkgf9tf8pl3chm7mkmqa5s30ydjdzx\\\"]\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"/regen.data.v1alpha1.Msg/SignData"}]},{"type":"regen.data.v1alpha1.EventSignData","attributes":[{"key":"cid","value":"\"AVUSIG5v95UKNhh6gBYTQm6Fjc5obNfX48D8Qu4DMActJFyV\""},{"key":"signers","value":"[\"regen:1qx9tsl46vkgf9tf8pl3chm7mkmqa5s30ydjdzx\"]"}]}]}],"info":"","gas_wanted":"200000","gas_used":"42240","tx":null,"timestamp":""}
```

**Comment by aaronc** [comment]
Thanks @clevinson. I considered those could be unpleasant trade offs but opted for binary anyway.... More broadly is CID even the right standard. I'm honestly not sure and could explain more next week.
