### ISSUE TITLE
CLI: Creates a new credit class should support both binary and a text format

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#179]
## Description

Currently a metadata for `create-class` and `create-batch` command must be provided as a base64 encoded binary.
Let's consider supporting both a text format and a binary format.

Reference: https://github.com/regen-network/regen-ledger/pull/172#discussion_r526377155

**Comment by robert-zaremba** [comment]
@aaronc , questions: 

1. Do we prefer a binary flag (`--text-metadata`) ... or 2 flags - exatly one hast to be provided (`--text-metadata` and `--binary-metadata`)?
1. What should be the return format? Currently we JSON serialize the `ClassInfo` object and print it on the terminal. The `ClassInfo.Metadata` is `[]byte` so it will be serialized as `base64`.
1. Should we have a storage limit for the metadata? If yes, what's a good limit? 2KB?

**Comment by aaronc** [comment]
1. I'm thinking two flags
2. For now I guess we have base64 but it would be good to consider alternatives in the future
3. Sure. Although 2k is probably way too small for some accurate polygons over large area. Likely we need that metadata to live off chain and just be anchored on chain. Wdyt?

**Comment by robert-zaremba** [comment]
re 3. Not limiting is a vulnerability. I would keep it small and turn a gas meter on it. Then user should decide how to handle it and we should offer him some recommendations / solutions . This could be a part of the client CLI.

**Comment by aaronc** [comment]
Yeah so let's set a limit. It should be a param

**Comment by clevinson** [comment]
This is being addressed in the data moduel refactor.
