### ISSUE TITLE
Add max data size consts for x/data and x/ecocredit + additional gas for hash & storage

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#185]
We need to make sure that we have maximum size constraints for:
- [ ] ~~`x/data` `Msg/StoreRawData`~~
- [ ] `x/data` hash verification gas #934
- [x] `x/ecocredit` credit and batch metatdata

**Comment by clevinson** [comment]
the x/data side of this will be taken care of by @aaronc's `x/data` upgrades

**Comment by cyberbono3** [comment]
@aaronc can I start working on it?
