### ISSUE TITLE
Record credit retirement location

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#202]
In credit retirement, we aren't capturing the location where the credit beneficiary is claiming an offset. This is likely relevant for NDC accounting for the Paris Agreement and possibly for local alliances (like C40). So at a minimum we should include some location field for retirement messages - could be a geo-point or maybe simply a national or sub-national entity name.

**Comment by ruhatch** [comment]
@clevinson closing this, as I believe we've done this now
