### ISSUE TITLE
Add more CLI tests for x/data

### ISSUE THREAD

**Issue by amaurym** [regen-network/regen-ledger#205]
**Is your feature request related to a problem? Please describe.**

Recent weeks in cosmos sdk uncovered numerous regressions. Adding tests early on help catch them.

**Describe the solution you'd like**

More tests for x/data CLI:
- https://github.com/regen-network/regen-ledger/pull/176#discussion_r530896337
- https://github.com/regen-network/regen-ledger/pull/176#discussion_r530895649
- https://github.com/regen-network/regen-ledger/pull/176#discussion_r530885586

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by ryanchristo** [comment]
Closing this as (1) imports have been updated (2) a signer can successfully submit a message to sign having already signed and the signer address will be ignored (3) no longer storing data.
