### ISSUE TITLE
Remove `:` in regen bech32 prefixes (or not)

### ISSUE THREAD

**Issue by amaurym** [regen-network/regen-ledger#208]
**Is your feature request related to a problem? Please describe.**

From Simon (cosmjs):

> Speaking of convecntions, any chance you can propose the use of the regen bech32 prefix instead of regen:?
This colon is pure pain. It is a fake separator before the real separator 1
and prevents things like double click to select an address and https://github.com/CosmWasm/dApps/blob/v0.4.0/packages/logic/src/config.ts#L55-L62

I wasn't aware that the `1` was the real separator, I'm fine with removing `:`.

**Describe the solution you'd like**

Remove `:` in bech32 prefixes

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by aaronc** [comment]
The `:` turns the address into a URI which imho is highly desirable given that we want to work with linked data. And it allows us to prefix the address with `did:` and then we have a DID. What's the pain Simon has?

**Comment by aaronc** [comment]
If we don't use `:` we would need a totally different URI encoding that has no relation to bech32, maybe base58.

**Comment by amaurymartiny** [comment]
I'm not sure myself, don't want to be the messenger 😅 ... pinging @webmaster128 if you ever see this, or we can have a separate conversation on this e.g. on Discord.

**Comment by aaronc** [comment]
Can you follow up on this @amaurymartiny ? I'd like to make a decision ASAP. If we don't use `regen:` for bech32 we can use base58check for DIDs.

**Comment by robert-zaremba** [comment]
We are using `1` as a separator:
* example: `regen:1ky29knsw3l9veuvw6ehk9s0jxqkdpuuaet0tlz`  - prefix is: `regen:`, or for pubaddr: `regen:pub1addwnpepq0szr6u8fry23ssh0jprkal69n4vd3p7sn2zdd66xstd8j4e5wv870paxs6` - prefix is: `regen:pub`

Is the issue to not use `:` in the prefix? In fact, based on the prefixes construction and DID spec, and base32 we can use it. `:` is allowed in the first part (human readable) of base32.

> If we don't use `:` we would need a totally different URI encoding that has no relation to bech32, maybe base58.

@aaronc  I think we can still build URI on top of that. `bech32` should be only used for addresses and a DID can be build on top of that, right? 

Here is a DID syntax:
```
did                = "did:" method-name ":" method-specific-id
method-name        = 1*method-char
method-char        = %x61-7A / DIGIT
method-specific-id = *( *idchar ":" ) 1*idchar
idchar             = ALPHA / DIGIT / "." / "-" / "_"
```

bech32 address could be used as a part of a `method-specific-id`. So, practically speaking:
* method-name = "regen"
* method-specific-id = <type>:1<address>, example: type="pub", address="addwnpepq0szr6u8fry23ssh0jprkal69n4vd3p7sn2zdd66xstd8j4e5wv870paxs6"

example: base32 human_readable_part=regen:pub, sep=1, data="addwnpepq0szr6u8fry23ssh0jprkal69n4vd3p7sn2zdd66xstd8j4e5wv870paxs6"

**Comment by webmaster128** [comment]
Sorry for not getting back to you so far.

I must admit, using bech32 address as URIs is an interesting idea. I never though about this possibility. So if you have strong reasons do to this, feel free to close. Bech32 spec covers this.

My feeling seeing those addresses was always irritation. It felt like there is a fake separator between prefix and address, right next to the real separator `1`. Because of this extra colon you cannot double click to select the whole address.

Personally I would build URIs using `systen:address_on_system`, like `mailto:` and `tel:` URIs.

Anyways, I don't see super strong reasons to keep or change the current format.

**Comment by robert-zaremba** [comment]
I would strongly prefer to be DID compliant. Also it's worth to note, that DID can have more than one colon:
```
did:regen:<part1>:<part2>1<resource>
```
Another important point is that we can have multiple `1 but **only** the last 1 is the separator.

**Comment by aaronc** [comment]
Note that `AccAddressToDID` should be updated based on what we decide.

**Comment by aaronc** [comment]
Whatever we do, we need to decide it ASAP. Can other people chime in please?

I would like to know how it's going in the testnet for instance.

@clevinson @amaurymartiny @anilCSE @glandua please chime in with your thoughts.

If we're going to change it, it should likely happen before the next testnet.

So `regen:sdgkhsdgoiqeghdsghk` or regensdgkhsdgoiqeghdsghk` addresses? What will it be?

**Comment by anilCSE** [comment]
+1 for `regen:` prefix (with colon).

**Comment by robert-zaremba** [comment]
Similar discussion in https://github.com/cosmos/cosmos-sdk/discussions/8431#discussioncomment-394358
