### ISSUE TITLE
[x/group] Events

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-ledger#215]
- Add remaining event types for proposals and votes
- We could make the ids (group, proposal...) just `uint64` (ref: https://github.com/regen-network/regen-ledger/pull/220#discussion_r576875675)
- We could also add more info to the existing events which are pretty minimalist right now (ref: https://github.com/regen-network/regen-ledger/pull/154#discussion_r552025354)

ref: https://github.com/regen-network/cosmos-modules/issues/43

**Comment by aaronc** [comment]
In general I'm in favor of minimalist events which only contain indexable/observable fields, because the other info is elsewhere. So the question should really be - what is a client going to care to observe?
