### ISSUE TITLE
Support account upgrade from base account to group account

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#217]
Status: awaits solution from the Cosmos SDK side.

**Is your feature request related to a problem? Please describe.**
For mainnet we're expecting to have several important token pools managed by group accounts (both for internal pools, as well as community staking DAOs). It's important to have hardware wallet support for these accounts. However, it is unlikely that we will have support for `SIGN_MODE_DIRECT` or `SIGN_MODE_TEXTUAL` on Ledger Nano devices by the time mainnet launches, which means Ledger Nano would not support signing transactions containing Group Module msg's.

**Describe the solution you'd like**
Implement an upgrade path for normal accounts to be initiated, and then later upgraded to a group account. This would likely involve something similar to [ADR034](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-034-account-rekeying.md) (Account Rekeying)

**Describe alternatives you've considered**
An alternative approach could be implementing amino signing capabilities in the group module. We decided not to do this for IBC and in general for new modules, but could make an exception here.

**Comment by clevinson** [comment]
We should migrate this issue to the SDK once group module is moved over there.

**Comment by clevinson** [comment]
@blushi do you know if this is being spec'ed out or worked on in the group module work you've been doing on the SDK?

**Comment by aaronc** [comment]
Thread addresses the ledger signing problem only. There is currently no upgrade path, ADR 034 has not been implemented and there is no guarantee on when or if it will be. And there would need to be even more refactoring of the auth module to enable that. In short, I wouldn't expect any solution in the near term.

**Comment by ryanchristo** [comment]
It looks like we can move the discussion to https://github.com/cosmos/cosmos-sdk/discussions/8528 and track the implementation of ADR 034 in the sdk. Closing here as this no longer applies to the regen-ledger codebase.

**Comment by ryanchristo** [comment]
It looks like we can move the discussion to https://github.com/cosmos/cosmos-sdk/discussions/8528 and track the implementation of ADR 034 in the sdk. Closing here as this no longer applies to the regen-ledger codebase.
