### ISSUE TITLE
Integrate validator Dropbox Paper FAQ doc into documentation / testnets repo

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#227]
@robert-zaremba started collecting Validator questions and answers in a dropbox paper doc, and we should find a more long term home for this content. Probably best belong in docs.regen.network or testnets repo.

**Comment by robert-zaremba** [comment]
It's here: https://paper.dropbox.com/doc/Regen-Network-Testnet-FAQ-and-Troubleshooting--BD_VBvvkjHG5lXMoZTA64FADAg-5cZfXpQKdJYEY7gal2wGS
