### ISSUE TITLE
Register Regen as a DID method name

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#231]
### Is your feature request related to a problem? Please describe.

DID is getting more and more adoption. Many blockchains already registered it's name. We should register regen.

### Describe the solution you'd like**

Register `regen` as a method name through the  Ontology Foundation :
* https://w3c.github.io/did-spec-registries/#did-methods
* https://github.com/ontology-tech/DID-method-specs

**Comment by clevinson** [comment]
This is blocked on SDK/IBC level decisions about how DID method names will be used across all cosmos chains.

**Comment by ryanchristo** [comment]
https://github.com/cosmos/cosmos-sdk/issues/6168

**Comment by robert-zaremba** [comment]
note: we are implementing an x/nft module with IXO

**Comment by robert-zaremba** [comment]
BTW: this task is not implementation related.
