### ISSUE TITLE
Lookup table hash function

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#248]
As a follow-up to #234, make sure we've chosen the correct hash function for the lookup table: https://github.com/regen-network/regen-ledger/pull/234#discussion_r569881104.

**Comment by aaronc** [comment]
I think we should just use blake2

**Comment by robert-zaremba** [comment]
I would even go with [blake3](https://github.com/zeebo/blake3) and the 32-byte hasher. Had a chat with Jean-Philippe and they already us it at Kudelski.

**Comment by aaronc** [comment]
> I would even go with [blake3](https://github.com/zeebo/blake3) and the 32-byte hasher. Had a chat with Jean-Philippe and they already us it at Kudelski.

Not much benefit for this use case which is a very small input size I expect
