### ISSUE TITLE
Update to SDK v0.42

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#267]
- [ ] Bump dependency
- [ ] add in support for `x/authz` `x/fee_grant` to regen ledger (experimental features)

**Comment by clevinson** [comment]
v0.42.0-alpha1 is tagged on the SDK so we can bump now.

**Comment by clevinson** [comment]
We currently regen-ledger updated to v0.42.0-rc0, but should keep this issue open until the next SDK release, which will have an important fix to an issue with Tracking Delegation in vesting accounts.

**Comment by amaurym** [comment]
Superseded by https://github.com/regen-network/regen-ledger/pull/349
