### ISSUE TITLE
regen query tendermint-validator-set limits to 100, even when limit is set

### ISSUE THREAD

**Issue by gotjoshua** [regen-network/regen-ledger#272]
**Describe the bug**
regen query tendermint-validator-set limits to 100, even when limit is set

**To Reproduce**
`regen query tendermint-validator-set 100000 --limit 200 | jq '.validators | length' `                                                          
100
`regen query tendermint-validator-set 100000 --limit 100 --page 2 | jq '.validators | length' `                                             
8

**Expected behavior**
`regen query tendermint-validator-set 100000 --limit 200 | jq '.validators | length' `                                                          
108

**Additional context**
regen testnet

**Comment by aleem1314** [comment]
That's true. There is a maximum per page limit from tendermint side [maxLimit](https://github.com/tendermint/tendermint/blob/master/rpc/core/env.go#L129).
