### ISSUE TITLE
Blockchain data for credit issuance pop-up is not descriptive enough

### ISSUE THREAD

**Issue by rsteinhe** [regen-network/regen-ledger#275]
**Describe the bug**
See https://app.zenhub.com/workspaces/regen-registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-registry/368 
https://deploy-preview-487--regen-registry.netlify.app/projects/wilmot

1) Any way to replace the key values: 'batch-denom' is not really descriptive, used for credits to seller, buffer pool and reversal buffer ; can we add 'description' field to each key-value for clarity? i.e. class_id ; description 'CarbonPlus Grasslands'. Pretty much for every key-value we can have a human legible description field. 
2) Also, I see sender with value null/empty. So clarifying all this would be great.
3) Memo - I would add 'Credit Issuance to Wilmot' something that we can automate
4) Transaction fee - maybe just add mock data there for clarity e.g. number of tree/REGEN tokens ideally with exchange value to USD as well.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clevinson** [comment]
@rsteinhe closing this as it looks like this was addressed on Regen Registry
