### ISSUE TITLE
make test expects / creates nodeHomeDir in default directory (~/.regen) instead of TempDirs

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#286]
**Describe the bug**
Tests should be self contained. I originally noticed this issue in `app/regen/cmd/TestInitCmd()` and addressed in in #285.  But after clearing my go test cache realize that the problem still persists, and there are probably a number of CLI tests that expect (& create if doesn't exist) a config dir in $HOME.

We probably have to do some sleuthing around to find all tests that this applies to. I assume a similar problem exists on the SDK repo with `~/.simapp`.

**To Reproduce**
1. `rm -rf ~/.regen`
2. `make test`
3. `ls -l ~/.regen` (returns a valid config dir)

**Expected behavior**
`make test` should not interact with a user's local defaultNodeHome (e.g. `~/.regen`), and should rather create TempDirs.

**Comment by ryanchristo** [comment]
Unable to reproduce. It looks like we are using temp directories in all tests now.
