### ISSUE TITLE
Add homebrew formula & equivalent for linux

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#297]
For ease of downloading regen ledger, would be good to add homebrew formulas and equivalent prebuilt package hosting on linux.

**Comment by clevinson** [comment]
Seems like this should be pretty easy with goreleaser: https://goreleaser.com/customization/homebrew/

**Comment by likhita-809** [comment]
This issue was already addressed as a part of #303, maybe we can close this. Wdyt @anilCSE ?

**Comment by rickmanelius** [comment]
+1 on this for homebrew

**Comment by rickmanelius** [comment]
A quick review of goreleaser highlights that it is awesome, but has a few caveats.
* Need to get approval on price ($250/year for a Pro license).
* goreleaser takes over the generation of releases in GitHub (which may manual inspection to address copy).

I think it looks neat enough to get started on to see what it would look like on a repo fork.

**Comment by rickmanelius** [comment]
Yeah so it looks like the previous comment was correct in that it's already addressed in mainline by #303, but it won't be possible to test/verify until a new tag is generated and pushed. We will then need to verify that we can connect to homebrew with this alone OR if we have to make a dedicated homebrew-regen-ledger repo.
