### ISSUE TITLE
Avoid using reflection in orm.ImportTableData

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#309]
## Is your feature request related to a problem? Please describe.

Reflection moves problem solving from compile time to runtime. It's also less performant and more cryptic.
In `orm.ImportTableData` we relay on reflection,  where an iterator pattern is needed.

## Describe the solution you'd like

Instead of empty interface and reflections we can use one of:

* use `[]PrimaryKey`  (that would require copying slice all whenever we call this function - which shouldn't be a big deal, because we will only copy `len(slice)` pointers).
* or an interator pattern:

```
type NaturalKeyedIterator interface {
   Next() bool   // goes to the next element, returns false if there are no more elements
   Get() NaturalKeyed // returns current element
}

type MyObjs {
   slice []MyObj
   idx uint
}
func (m *MyObjs) Next () { 
    if m.idx >= len(slice) - 1 { return false }
    m.idx++
    return true
} 
func (m *MyObjs) Get() NaturalKeyed {  return m.slice[m.idx] }
```

ref: https://github.com/regen-network/regen-ledger/pull/270#discussion_r597934655

**Comment by robert-zaremba** [comment]
Since this is only used for imports, I think we can easily copy the the slice. It really doesn't impact much the memory (I would argue that it won't impact at all, because we won't do reflection and do less allocations in total).

What do you think? @blushi , @amaurym , @aaronc

**Comment by aaronc** [comment]
I'd actually like to switch the orm to use code generation from a table descriptor (probably a simple yaml file) which would avoid reflection entirely and likely bring other benefits in terms of type safety and ability to index in a sql database.

**Comment by ryanchristo** [comment]
Closing this issue as we have since implemented code generation from a table descriptor.
