### ISSUE TITLE
readme not updated for deprecated  cli commands  and connID mismatch 

### ISSUE THREAD

**Issue by GrandGarcon** [regen-network/regen-ledger#323]
**Describe the bugs**
- the command `regen gentx $KEY_NAME --amount 100000stake --chain-id [chain-id]`  mentioned in the readme is not compatible to the present regex pattern of the cli command : `regen gentx [key_name] [amount] [flags]`

- also currently i am facing issue of the localnode not able to connect to the testnet peer node , after following the steps of generating the genesis file with the peer infomration , i get the following logs  on chain-id `regen-devet-5`  :

```json 
6:03PM ERR dialing failed (attempts: 1): auth failure: conn.ID (b2679a74d6bd9f89a3c294c447d6930293255e6b) dialed ID (a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb) mismatch addr={"id":"a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb","ip":"18.220.101.192","port":26656} module=pex
6:03PM INF Reconnecting to peer addr={"id":"a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb","ip":"18.220.101.192","port":26656} module=p2p
6:03PM INF Dialing peer address={"id":"a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb","ip":"18.220.101.192","port":26656} module=p2p
6:03PM INF Error reconnecting to peer. Trying again addr={"id":"a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb","ip":"18.220.101.192","port":26656} err="auth failure: conn.ID (b2679a74d6bd9f89a3c294c447d6930293255e6b) dialed ID (a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb) mismatch" module=p2p tries=0
6:03PM INF Dialing peer address={"id":"a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb","ip":"18.220.101.192","port":26656} module=p2p
6:03PM ERR Error dialing peer err="auth failure: conn.ID (b2679a74d6bd9f89a3c294c447d6930293255e6b) dialed ID (a621e6bf1f5981b3e72e059f86cbfc9dc5577fcb) mismatch" module=p2p



```

**reproduction steps**
Followed the getting started tutorial  from the regen-ledger community

**additional information**
[link](https://pastebin.com/aN2qeXxM) of my my genesis account file  

**recommendation**

readme updation and checking the bug causing the invalid is's during connection .

**Comment by robert-zaremba** [comment]
Thanks @GrandGarcon  for reporting.

**Comment by robert-zaremba** [comment]
README was updated. Instead of `100000stake` there should be `100000uregen`
