### ISSUE TITLE
Record retirement location for ecocredit module

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#328]
Retirement location should be stored & recorded. This should be a location of:
- beneficiary
- buyer

Paris Agreements require to track where we require credits (jurisdiction / sub national, eg: NY State can have different accounting than New Jearsy or New York City).
We need short, not ambiguous field for location. 
We propose:
```
<country-code>[-<sub-national>-[<postal-code>]]
```
The former two are codes specified by [SO_3166-2](https://en.wikipedia.org/wiki/ISO_3166-2)

**Comment by clevinson** [comment]
Some refinement here:
- issuance location (geopolygon) will be taken care of via shacl schemas on data module, and are out of scope for this issue, though still a requirement

Adding one field on retirement for location, it should be strings adhering to something similar to: https://en.wikipedia.org/wiki/ISO_3166-2

**Comment by ruhatch** [comment]
A couple of refinement questions here:

**1. Should we record the location in the store?**

We are going to log the location in events, so we can access location information using an index of events, but that might make quick access more difficult. In general, we'd like to store as little as possible in state, so to stick with that design principle we would err on the side of not putting locations in the store. If it's really bad for end-user experience, then we can add them into the store, and we can always do this at a later date, as it doesn't affect the actual chain.

**2. Should we record locations for retired_units in MsgCreateBatch and MsgSend?**

Both these messages include credit retirement during the issuance or transfer of credits from a batch. It seems we therefore need to include retirement location alongside those credit retirements, but I want to check that this is desired behaviour. @clevinson @blushi would you be able to check this with Ron?
