### ISSUE TITLE
ConvertAndEncode and DecodeAndConvert  functions inside util/utils.go

### ISSUE THREAD

**Issue by cyberbono3** [regen-network/regen-ledger#331]
Working on #322, @clevinson and me noticed that
[ConvertAndEncode](https://github.com/regen-network/regen-ledger/blob/1b7c80ef102d3ae7cc40bba3ceccd97a64dadbfd/util/utils.go#L12) and [DecodeAndConvert](https://github.com/regen-network/regen-ledger/blob/1b7c80ef102d3ae7cc40bba3ceccd97a64dadbfd/util/utils.go#L22) functions are never called within regen-ledger. 

Do we wanna keep them or remove them from the codebase?

**Comment by ruhatch** [comment]
`Uint64ToBase58Check` is also unused, so we should be able to delete this whole file

**Comment by ruhatch** [comment]
Closed by #492
