### ISSUE TITLE
Upgrade to 0.43-beta1 and integrate x/authz & x/feegrant into stable

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#336]
his is ready to start ASAP now that 0.43-beta1 is out.

Important notes:
* this will require a release of ibc-go: https://github.com/cosmos/ibc-go
* we need to setup an upgrade handler that runs migrations
* in the upgrade handler, we need to skip the `x/auth` `ConsensusVersion` upgrade because we patched this into regen-ledger v1.0 (cc @amaurym @technicallyty)

Here's the WIP 0.43 gaia PR: https://github.com/cosmos/gaia/pull/834 for reference

**Comment by aaronc** [comment]
@robert-zaremba, @likhita-809 had already starting working on this integration in #329 and is going to continue working on that PR

**Comment by likhita-809** [comment]
> @robert-zaremba, @likhita-809 had already starting working on this integration in #329 and is going to continue working on that PR

Started working on this

**Comment by robert-zaremba** [comment]
I think testing IBC is _nice to have_ for our team. Instead we should collaborate with the IBC team.
