### ISSUE TITLE
Makefile targets should cover all go modules

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#337]
In #322 we missed updating the `Makefile` so that the `test` target. We need `Makefile` and CI tests to cover all go modules.

**Comment by cyberbono3** [comment]
@aaronc, can you give more context on this, please?

**Comment by aaronc** [comment]
When you run `go test .\...` that only runs tests in the current go module. That is what is happening in the Makefile and CI. We need _all_ go modules tested so the script needs to `cd` into each folder.

**Comment by cyberbono3** [comment]
> `go test .\...`

When I run `find . -name go.mod -execdir go test ./... \;`, i get the following [output](https://play.golang.org/p/u-hAPH6MZ4E). Does it make sense?

**Comment by blushi** [comment]
@cyberbono3 can we try to fix this asap? it's a bit blocking on other PRs where we cannot actually check if all the tests are passing or not.
