### ISSUE TITLE
0.43 chain upgrade test

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#340]
* export genesis.json from regen network's mainnet
* patch the genesis.json with a new validator set that we can run as a devnet, and we reduce the voting window to 30-60 minutes
* spin up a devnet with regen-ledger 1.0
* run an upgrade proposal against a version of regen-ledger with 0.43 so that migrations get run
* do manual testing against the upgraded regen network devnet (see https://github.com/cosmos/cosmos-sdk/issues/9116). Existing modules should be tested FIRST, new modules SECOND

needs #336

**Comment by amaurym** [comment]
Can we close this? Our devnet upgraded successfully

**Comment by anilCSE** [comment]
> Can we close this? Our devnet upgraded successfully

Yes
