### ISSUE TITLE
Add fixed fee for creating a new credit class

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#351]
At first this should just involve sending fees to the fee pool, but eventually could change to send fees to some "credit class governance body" who stewards the larger set of on-chain credit classes.

- [ ] write specification
- [ ] decide about the pledge mechanism
- [ ] decide about the community pool

**Comment by robert-zaremba** [comment]
Fee should be on-chain parameter - governed by REGEN holders.
TODO: need to decide about the process and what happens with the fee (burned vs some pool).

**Comment by robert-zaremba** [comment]
Here is my proposal for what to do with fees:
* 34% will be burned
* 66% will go to a community pool. Funds from this pool will be used create gitcoin grants for building ecosystem around eco-credits.

**Comment by ruhatch** [comment]
I've opened [a discussion](https://github.com/regen-network/regen-ledger/discussions/383) to continue making the decision about what to do with the fees.
