### ISSUE TITLE
Move away things from x/group/exported

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#353]
## Is your feature request related to a problem? Please describe.

Exported package doesn't make much sense. In group it's used to describe a dependency for the group module. So it can be in the group module package itself. 
Moreover, it doesn't export any useful type outside

Using `exported`, as a package name is not idiomatic, and it's blizzard..

## Describe the solution you'd like

Move away things from `exported` package.

**Comment by ryanchristo** [comment]
This has been resolved in the sdk implementation.
