### ISSUE TITLE
Indexing of on-chain graphs to Postgresql

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#38]
This is to support the generation of maps for visualizing ecological state claims.

On-chain graph data should be indexed to Postgresql in the `data` table which should look something like this:

```
CREATE TABLE data (
  address bytea NOT NULL PRIMARY KEY,
  data jsonb, -- for on-chain graphs
);
```

The graph should be serialized as JSON-LD in expanded document form.

**Comment by clevinson** [comment]
@aaronc should this get closed ?
