### ISSUE TITLE
Add migrations for CreditClassFee param

### ISSUE THREAD

**Issue by ruhatch** [regen-network/regen-ledger#381]
#375 adds a fixed fee for creating a new credit class, based on a global param, updated through governance. This param represents a breaking change that requires an update/migration, so we need to add both:
- JSON migration
- In-place store migration

**Comment by aaronc** [comment]
I’m not sure we need an in place migration for the params module. We don’t need a json migration because there are no production chains using this.

**Comment by ruhatch** [comment]
> I’m not sure we need an in place migration for the params module. We don’t need a json migration because there are no production chains using this.

Hmm, how will our regen ledger mainnet become aware of this parameter when we update?

**Comment by ruhatch** [comment]
There'll be no need to do migrations, because there is no export genesis in the current chain. Init genesis will be called on the new module and will have the default values of the param.
