### ISSUE TITLE
Add support for credit cancelling

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#385]
We should add basic functionality in the ecocredit module whereby:
- the holder of credits can cancel their own credits (any number of credits that are unretired)

Down the road we may want to add functionality for issuers to cancel credits as well, but more requirements need to be assessed before this gets implemented.

**Comment by aaronc** [comment]
This would probably look like adding `MsgCancel`:

```proto
message MsgCancel {
  string holder = 1;
  repeated Unit units = 2;

  message Units {
    string batch_denom = 1;
    string amount = 2;
  }
}
```

**Comment by robert-zaremba** [comment]
Only token owner can cancel his tokens.

**Comment by robert-zaremba** [comment]
When cancelling we:
* reduce supply 
* subtract /remove balance
