### ISSUE TITLE
Explicit credit class units

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#398]
Currently, we have all information on credit classes in metadata which is currently unspecified for the state machine. It would be nice to have some high-level explicit information on the units of credits in `MsgCreateClass`, e.g. "carbon tons".

One reason for not including this explicitly is that I think an `enum` is too limiting and would require a software upgrade to support more credit types.

I propose instead that we have:
* param which is a list of strings for credit units. Ex: `["carbon tons", "biodiversity hectares"]`
* a new field `unit` on `MsgCreateClass`

The list of approved units/types could then be updated by governance without a chain upgrade.

**Comment by aaronc** [comment]
@clevinson ?

**Comment by clevinson** [comment]
Should we also distinguish between units and measure (maybe there's a better name for this)?

e.g. "carbon tons" and "carbon kg" have a direct exchange rate / relationship that can be quantifiable. Wouldn't we be better off storing this as something like `{"measurement": "carbon", "unit": "ton"}` ?  Maybe with some feature similar to denomMetadata in bank where we can register base units & exponents?


It may not seem necessary now, but I think we do want to be flexible to location specific standards in the long term. And while CO2 may have standardized around tonnes, other measurements may have standard units in imperial verses metric system based on what country the assets are being issued in.

**Comment by clevinson** [comment]
I guess I see this as pretty essential for the `x/basket` module design you proposed, so happy to move forward w/ this in one form or another.

**Comment by aaronc** [comment]
Replaced by #424
