### ISSUE TITLE
Postgrest & Postgraphile servers for Postgresql blockchain index

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#41]
This is a devops task primarily and would involve configuring a Postgrest and Postgraphile instance in `module.nix` for the Postgresql blockchain index. These should be enabled whenever the index is enabled and only deal with authenticating a public, read-only user - because the whole index is available for anyone to query and is read-only. Should be pretty straightforward, no need to deal with any of the JWT authentication stuff for these services.

Also worth considering an integration of something like https://github.com/go-spatial/tegola or https://github.com/urbica/martin for generation of Mapbox Vector Tile from Postgis, or tracking that for later

**Comment by clevinson** [comment]
@aaronc should this get closed ?

**Comment by aaronc** [comment]
It actually is still relevant.
