### ISSUE TITLE
Ecocredit simulations

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#416]

**Comment by clevinson** [comment]
@anilCSE @aleem1314 Do either of you know how easy it is for us to start doing simulations on Regen Ledger?

**Comment by blushi** [comment]
@aleem1314 added simulations for x/group within Regen Ledger, it's basically set up the same way as init/export genesis by registering the `WeightedOperations` function from the server.

Maybe @aleem1314 or @atheeshp could work on this?

**Comment by atheeshp** [comment]
> @aleem1314 added simulations for x/group within Regen Ledger, it's basically set up the same way as init/export genesis by registering the `WeightedOperations` function from the server.
> 
> Maybe @aleem1314 or @atheeshp could work on this?

Yeah, I can take up.

**Comment by aleem1314** [comment]
This is blocked by #389 #428 .

**Comment by blushi** [comment]
Good point @aleem1314, that's what I realized afterwards.
I linked those dependencies on zenhub.
