### ISSUE TITLE
tests: Add more tests to `ecocredit` package

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-ledger#423]
The test coverage is quite low at the moment in `x/ecocredit`, e.g. msgs `ValidateBasic()` are not being tested.
It would be good to add more unit tests to this package.

ref: https://github.com/regen-network/regen-ledger/pull/421#issuecomment-881350957

@aaronc @clevinson do we want to tag that for v1.1?

**Comment by aaronc** [comment]
Thank you! Yes please
