### ISSUE TITLE
Add permissions for credit class creation

### ISSUE THREAD

**Issue by ruhatch** [regen-network/regen-ledger#425]
## Background

We haven't finalised the design of credit classes, but we want to release something for community/stakeholder feedback. We can release something, but maintain the ability to change it later by adding a whitelist of credit class designers, containing only RND keys. This gives us central control over credit creation, which allows us to tweak the design based on feedback.

## Implementation

To do this we need to:
- [ ] Add a credit class designers whitelist as a governance parameter
- [ ] Check that designers are on the whitelist when creating classes

**Comment by ruhatch** [comment]
@aaronc should we store the whitelist as a governance parameter or just hardcoded perhaps?

**Comment by aaronc** [comment]
As a governance parameter

**Comment by technicallyty** [comment]
should there also be a gov param to whether this allowlist is turned on or off? or maybe if the `len(allowlist) == 0` means its off?

**Comment by aaronc** [comment]
Maybe, but I think we want empty allow list to actually mean no credit classes can be created. It may be that way when we launch. So maybe there's another bool to allow all addresses.
