### ISSUE TITLE
add list of eco credit measurement units for validation

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#429]
## Summary

add a list of valid SI units for credit type validation

## Problem Definition

in https://github.com/regen-network/regen-ledger/pull/428 we implemented credit types as a governance param which include SI units such as kg, ton, etc for each type. It would be nice to validate these parameters with a canonical list of valid SI units

## Proposal

add a list of valid SI units similar to below:
-  http://qudt.org 
-  https://github.com/BertVerhees/ucum
-  https://ucum.org/trac

```go 
if _,ok := validSIUnitMap[creditType.Unit]; ok {
 // yay
}
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
I would consider this nice to have

**Comment by ryanchristo** [comment]
I think this might need more consideration. When attempting to write an example for biodiversity, I was not sure how to define the unit and whether that unit would fall under the SI. We also include "of carbon" in our current credit type. I'm going to move this issue out of our current v4.0 milestone and maybe discuss with Sam before someone picks it up.

**Comment by aaronc** [comment]
Having on chain validation is probably too restrictive. For instance is the unit for carbon "ton" or "metric ton CO2e". I think the latter is more useful and would fail unit validation
