### ISSUE TITLE
v2.0 Release QA

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#434]
v2.0 Release Team: @clevinson, @anilCSE, @ruhatch, @kaustubhkapatral

## `beta` releases
- [x] Tag `beta1` off `master`.
- [x] Existing code changes Audit (for non-new modules. e.g. everything other than x/ecocredit)
  - [x] Modules state machine audit (if changed) - @clevinson 
    - [x] checking upgrade handlers for state are setup correctly
  - [x] API change audit: ensure new changes are well-named, documented and complete - @kaustubhkapatral, @anilCSE 
  - [x] Ensure proper unit, integration and simulation test coverage for new or changed features - @ruhatch 
- [x] Ensure all API breaking changes in SDK are handled, and changes to SDK simapp are reflected in app.go
- [x] Release Readiness (for x/ecocredit & x/orm)
  - [x] x/ecocredit #350 
  - [x] x/orm #455
- Between the `beta` and `rc` releases, we freeze the `master` branch from any kind of state-breaking changes. Client-breaking changes and small API-breaking changes can still be merged into master.
- [x] Run devnets & testnets
  - [x] All features and fixes in the `Unreleased` section of the Changelog should be tested.
  - [x] Test migration of existing state to new state.
- Note: Multiple `beta` releases can be tagged (always off `master`) if needed.

### 2.0-beta test net and simulation

- Regen Network
  - [x] testnet setup
  - [x] manual testing
  - [x] simulation done

## `rc` releases
- Unless there's a strong requirement otherwise, `release/v2.x` should be focused on bugfixes and final polishes. PRs are to be merged into `master` and backported to `release/v2.x`. Client-breaking changes and small API-breaking changes can still be merged back into the release branch if deemed necessary.
- [x] Audit Changelog against commit log, ensuring all breaking changes, bug fixes, and improvements are properly documented @clevinson 
- [ ] translate relevant changelog entries into acceptance tests (in issue) + link to x/ecocredit acceptance tests for manual testing
- [ ] Run devnets & testnets @kaustubhkapatral 
  - [ ] All features and fixes in the `rc` section of the Changelog should be tested.
  - [ ] Test migration of existing state to new state (using RC of cosmovisor 1.0)
  - [ ] Full round of tests against written acceptance tests
- Note: Multiple `rc` releases can be tagged if needed.
- In the case where both following conditions are met: 1/ a significant number of PRs are merged into `master` between two RC releases and 2/ none of those PRs are state-breaking; then the release team can decide to `reset --hard` the `release/v2.x` branch to point to `master`.

## `v2.0.0` release 
- [ ] Merge all Changelog entries from all `rc` releases into one `v2.0.0` section
- [ ] Merge and synthetize RELEASE_NOTES.md from all `rc` releases
- [ ] Tag off `v2.0.0` from the `release/v2.0.x` branch.

**Comment by ruhatch** [comment]
Test Coverage Report
-----------------------------

- `app`
  - `export.go`
    - The `prepForZeroHeightGenesis` function is untested, but mentions in docs that it is to be deprecated
  - `regen/cmd/`
    - `genaccounts.go`
      - The body of the `AddGenesisAccountCmd` is untested
    - `root.go`
      - The `newApp` and `createRegenappAndExport` functions aren't tested
- `orm`
  - `table.go`
    - Could test the nil values in `NewTableBuilder`
  - `index.go`
    - Could test the nil values in `newIndex`
  - `indexer.go`
    - Could test the nil values in `NewIndexer` and `NewUniqueIndexer`
  - `iterator.go`
    - Could test some nil values in here
  - `sequence.go`
    - Could test unique constraint in `InitVal`
- `math`
  - `dec.go`
    - **Should** test error cases in `*FromString` functions
  - `math.go`
    - Being deprecated, but `ParseNonNegativeFixedDecimal`, `ParsePositiveFixedDecimal`, and `requireMaxDecimals` are untested

Test coverage looks pretty good in general. There are a few things we can add and nothing too complicated, so I reckon we could cover everything listed above in one fairly small PR. I haven't done a deeper look at what kind of test values are covered in the tests, so I suggest we do a deeper audit on that, but wanted to put this initial survey in first.

This doesn't include stuff from experimental module wiring (`experimental_appconfig`, `types/module/server`, etc.).

**Comment by robert-zaremba** [comment]
QA Team board: https://www.notion.so/regennetwork/Regen-2-0-Release-26fbd0ad2f1242cc826c9c7c21aff5f7
