### ISSUE TITLE
Update v2.0 UpgradeHandler with regen specific stores

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#437]
- [x] migrate ecocredit module to base config (in [app.go](https://github.com/regen-network/regen-ledger/blob/master/app/app.go#L113-L133)), and remove from experimental_app_config
- [ ] stable config UpgradeHandler
  - [ ] ecocredit initgenesis (ensure default param for `allowlist_enabled` is overriden, and set to true)
  - [ ] ensure auth/vesting bug fix migration (v0.43) doesn't run

**Comment by aaronc** [comment]
We also need to make sure that the auth/vesting bugfix migration doesn't run because we used a fork with the bugfix. I think we just need to setup the initial version map correctly. /cc @amaurym

**Comment by blushi** [comment]
>  Add migrations for all existing credit vintages (cc @blushi)

@clevinson it seems like this issue is a bit out of date, since we decided that I'm going to re-do the transactions manually on the new devnet, could you update the description above please?

**Comment by clevinson** [comment]
Yep! Updated now, thanks @blushi

**Comment by clevinson** [comment]
Maybe we could actually delete the experimental_config upgrade handler entirely?

**Comment by amaurym** [comment]
> Maybe we could actually delete the experimental_config upgrade handler entirely?

x/group's integration testsuite actually only runs in experimental, so we should keep it for now. https://github.com/regen-network/regen-ledger/blob/7287f51c14838f28fafb2ce9514b68aaaa6d97dd/app/testsuite/modules_test.go

**Comment by amaurym** [comment]
> Maybe we could actually delete the experimental_config upgrade handler entirely?

Oh I misunderstood! Yeah, we can remove the upgrade handler in experimental_config!
