### ISSUE TITLE
Fix Regen Ledger lint errors and add `golint` CI task

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#44]
We want to be able to run `golint ./...` in CI. This mostly checks that all modules have appropriate doc strings. So this issue is mostly about adding missing source code documentation.

Definition of Done:
- [ ] you can run `golint ./...` from the project root and there are no errors
- [ ] there is a new CI stage that runs `golint ./...`. We should probably do this with https://github.com/golangci/golangci-lint instead of golint directly

**Comment by clevinson** [comment]
@aaronc should this get closed ?

**Comment by aaronc** [comment]
I think it's still relevant.

**Comment by aleem1413** [comment]
This issue addressed in this [golangci-lint](https://github.com/regen-network/regen-ledger/pull/112/commits/6d974750cc7d8c2e6c380005b96e722490576b65) PR.
