### ISSUE TITLE
make install doesn't build 'regen'

### ISSUE THREAD

**Issue by frumioj** [regen-network/regen-ledger#441]
## Summary of Bug

I followed the instructions at: https://docs.regen.network/getting-started/#install-regen but they appear to be incorrect.

'make install' does not build the regen executable:
```
frumiousj@dirtycomputer regen-ledger % ls -la build           
ls: build: No such file or directory
frumiousj@dirtycomputer regen-ledger % make install           
mkdir -p /Users/frumiousj/src/regen-ledger/build/
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=regen -X github.com/cosmos/cosmos-sdk/version.AppName=regen -X github.com/cosmos/cosmos-sdk/version.Version=v1.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=1b7c80ef102d3ae7cc40bba3ceccd97a64dadbfd -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath  ./...
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
frumiousj@dirtycomputer regen-ledger % ls -la build       
total 0
drwxr-xr-x   2 frumiousj  staff    64 Jul 28 11:43 .
drwxr-xr-x  38 frumiousj  staff  1216 Jul 28 11:43 ..
```
'make build' does though - should 'make install' depend on 'make build'?:

```
frumiousj@dirtycomputer regen-ledger % make build
go build -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=regen -X github.com/cosmos/cosmos-sdk/version.AppName=regen -X github.com/cosmos/cosmos-sdk/version.Version=v1.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=1b7c80ef102d3ae7cc40bba3ceccd97a64dadbfd -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath -o /Users/frumiousj/src/regen-ledger/build/ ./...
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
frumiousj@dirtycomputer regen-ledger % ls -la build
total 93160
drwxr-xr-x   3 frumiousj  staff        96 Jul 28 11:44 .
drwxr-xr-x  38 frumiousj  staff      1216 Jul 28 11:43 ..
-rwxr-xr-x   1 frumiousj  staff  47697904 Jul 28 11:44 regen
```
None of them causes the 'regen' executable to be in my path which means that the instructions to run `regen version` from my regen-ledger directory will not work, but it will work from the build directory - should make install change the user's path, or put the regen executable in a location that is on the user's path?:

```
frumiousj@dirtycomputer regen-ledger % regen version
zsh: command not found: regen
frumiousj@dirtycomputer regen-ledger % build/regen version
v1.0.0
```
## Version

git checkout v1.0.0

## Steps to Reproduce

Follow the instructions at https://docs.regen.network/getting-started/#install-regen
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by frumioj** [comment]
The description is actually incorrect, but there does seem an issue here:

1. `make install` does build the executable, in place in `$(go env GOPATH)/bin`
2. `make build` builds the executable in `regen-ledger/build`

`build` and `install` targets seem essentially unrelated.
Typing `make` on its own results in `make all`

Normal `make` behaviour (in my experience anyway) is that:

i) `make` should build the executable in the build output directory
ii) `make install` should install the built executable from the build output directory

**Comment by clevinson** [comment]
I'm in favor of cleaning up / aligning our makefile with best practices, and what you wrote out makes sense to me.

Should be noted- that our Makefile structure is more or less copied over from SDK, so if we're making meaningful changes to how we structure the basic make commands, we might want to do that on the SDK as well.
