### ISSUE TITLE
ORM Tables can't handle key which is prefix of another

### ISSUE THREAD

**Issue by ruhatch** [regen-network/regen-ledger#456]
## Summary of Bug

`PrimaryKeyTable`s in the `orm` package cannot have keys where one is a prefix of another. For example, if there is already a key `AA` in the table, then the table will claim to already have the key `A` in the table. Calling `Create` on an object with primary key `A` would then fail, because it would violate the unique constraint.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clevinson** [comment]
@blushi Was the latest from your conversations with Ru that this needs to be addressed as part of v2.0?

**Comment by blushi** [comment]
> @blushi Was the latest from your conversations with Ru that this needs to be addressed as part of v2.0?

yeah just opened up a PR for that #475
