### ISSUE TITLE
Find better way to set params for module testing

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#457]
## Summary of Bug

We have introduced a few new params into the ecocredit module, as well as add integration tests. In order to run these tests properly, we need to have some of our Params set properly. These params include:

- Allowlist (enabled/disabled)
- CreditTypes 

Some tests require creating classes, which require having an existing credit type to create with, and having the allowlist disabled. 

To fix this issue we can:
- Set the default params to something easy to test with ie. set allowlist enabled to false, and set a test credit type for use in the integration tests. 

the issue then becomes: how are these defaults used when we ship updates? would we have to manually revert the defaults so that the chain launches with an enabled allowlist and empty credit types (or whatever else sane default we want to ship with). Or are the params decided by an upgrade handler/ genesis file?

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clevinson** [comment]
> the issue then becomes: how are these defaults used when we ship updates? would we have to manually revert the defaults so that the chain launches with an enabled allowlist and empty credit types (or whatever else sane default we want to ship with). Or are the params decided by an upgrade handler/ genesis file?

The two main use cases for default param values are:
1. testing (like what we're talking about here)
2. creating new genesis files
3. potentially in upgrade handlers


For both (1) and (2) it makes sense to use defaults that are convenient for testing and for new users starting local chains (primarily also for testing).

You can imagine some users wanting to play around with credit modules against a local testnet, and if credit class creation is permissioned by default, then every user would either need override the default in their genesis.json file after they create one via `regen init` / `regen collect-gentxs`, or perform param-change gov proposal on their local net. The same goes for setting credit types.

For (3) I think it's actually pretty easy for us to set the values to what we want explicitly in the upgrade handlers for specific networks (mainnet and potentially testnet upgrades).  So I think its fine for us to prioritize defaults that will give end users a good experience when doing local testing, as opposed to necessarily setting them to our expected mainnet values.

**Comment by ruhatch** [comment]
@clevinson great, thanks for clarifying that!

@technicallyty I guess that means we should just set easy defaults in #426 and we can remove some of the dirtier module dependency and network testutil hacks :)

**Comment by technicallyty** [comment]
closing this as default params look like the best/easiest way to setup clean tests
