### ISSUE TITLE
Research Story: Walkers Pilot, Ecocacao Schema Draft

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#46]
# Definition of Done
* support for the Walker's & Ecocacao data schema 
* work with Gisel 
  * acquire walker's data
  * understand which elements of the schema are universal (may apply to other esp's)
* walker data stored and accessible to all (possibly a Github repo or pushed to an existing repo)
* requirements and architecture document
  * review and understand what changes to schema module are anticipated
  * class primatives

## Questions
* confirm with Gregory, that Walkers data can be public? (e.g. store on public testnet, in our app, where are boundaries such as public info)
* provide a link to sentinel / planet imagery in claim evidence?
* will map viewed allow navigating link above?

Clarification here: https://docs.google.com/document/d/1dEjc7jnO2MgsuMaz4lSpj0VxNXtLuYk3KVX36Qu2ZII

**Comment by clevinson** [comment]
@aaronc should this get closed ?
