### ISSUE TITLE
Some x/group LegacyAmino Msg type names are too long and break Ledger Nano signing

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#468]
## Summary of Bug

Ledger Nano has a hard limit of max 39 characters for Msg type values, and will fail with a “Error: Unrecognized error code” in the CLI when trying to sign a message with a registered Msg name that is too long.

## Version

`master`

## Steps to Reproduce

The Msg names passed to `cdc.RegisterConcrete()` in `RegisterLegacyAminoCodec()` implementations is used on Ledger Nano devices to display to the user the "Type" of message that they are signing.  If the Msg name (e.g. `cosmos-sdk/MsgSend`) is longer than 39 characters, the Ledger will return an error and the CLI signing will fail.

The following steps to reproduce do not require connecting to a live node, simply build from master (`make build`), and run the `regen` commands below.

Setup a ledger key (if you don't have one already), and set it to an env variable):
```
regen keys add ledger_testing --ledger
```

Given the following generated tx file (`short-msg-name.tx`):
```
{"body":{"messages":[{"@type":"/regen.group.v1alpha1.MsgUpdateGroupAccountAdmin","admin":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd","address":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd","new_admin":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}
```

The following command should successfully get sent to a Ledger Nano device:
```
regen tx sign short-msg-name.tx --chain-id test --from {ledger_testing or $YOUR_LEDGER_KEY_NAME} --offline --account-number 0 --sequence 0
```

However, given the following generated tx file (`long-msg-name.tx`):
```
{"body":{"messages":[{"@type":"/regen.group.v1alpha1.MsgUpdateGroupAccountMetadata","admin":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd","address":"regen1mrvlgpmrjn9s7r7ct69euqfgxjazjt2l5lzqcd","metadata":"bmV3IG1ldGFkYXRh"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}
```

The following command will fail to render on the Ledger Nano device, and instead will return an error:
```
regen tx sign long-msg-name.tx --chain-id test --from  {ledger_testing or $YOUR_LEDGER_KEY_NAME}  --offline --account-number 0 --sequence 0
```

Error:
```
Error: Unrecognized error code
```

The reason the second case fails, is that the [Msg type name](https://github.com/regen-network/regen-ledger/blob/master/x/group/codec.go#L24) of the `MsgUpdateGroupAccountMetadata` that is used for registering a concrete type with the `LegacyAminoCodec` is > 39 characters. (in this case, `"cosmos-sdk/MsgUpdateGroupAccountMetadata"` is 40 characters.

## Proposal 

We should change any of the group module Msg names necessary in order to ensure that all Msg names for `LegacyAminoCodec` registration in [codec.go](https://github.com/regen-network/regen-ledger/blob/master/x/group/codec.go#L24) have max 39 characters.

It would be also great to add a test if possible that ensures this, so that CI will fail if we have any MsgTypes names in the LegacyAminoCodec that are > 39 chars.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by blushi** [comment]
@clevinson We do already have CLI tests that uses amino-json signing for all group msgs but since this issue is device specific, the tests are just passing. I'm not sure how we could properly test that unless we hardcode this max number of characters somehow...

**Comment by amaurym** [comment]
Oh wow, nice find! I noticed that there were Msgs in the SDK with >39 chars, e.g. [MsgWithdrawValidatorCommission](https://github.com/cosmos/cosmos-sdk/blob/9fd866e3820b3510010ae172b682d71594cd8c14/x/distribution/types/codec.go#L16). Probably no-one ever sent a ledger tx with this Msg.

Do you have an idea where this number of 39 comes from?

**Comment by ryanchristo** [comment]
It looks like the group module messages have been updated and the larger issue is being tracked in the sdk.
