### ISSUE TITLE
Add RegisterLegacyAminoCodec implementation for x/ecocredit Msg's & types

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#469]
Many actions on the ecocredit module will initially be done by RND, likely through hardware wallet (e.g. Ledger nano S). In order for Ledger Nano S devices to be able to sign Msg's, they need to support `amino-json` sign mode.

To do this, we should:
- Add an implementation of `RegisterLegacyAminoCodec()` to [x/ecocredit/codec.go](https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/codec.go), akin to how we do so in [x/group/codec.go](https://github.com/regen-network/regen-ledger/blob/master/x/group/codec.go#L11-L28)
- Ensure all Msg type name's are not >39 characters (this breaks Ledger Nano support) as discovered in #468 

Is there anything else necessary for this? cc @blushi @amaurym ?

**Comment by clevinson** [comment]
Also, I'm noticing that [x/ecocredit/codec.go](https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/codec.go) looks pretty empty in general. Should we be also registering all the `Msg` types as implementations of the `*sdk.Msg` interface with the normal `codec.InterfaceRegistry` ?

**Comment by blushi** [comment]
> Also, I'm noticing that [x/ecocredit/codec.go](https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/codec.go) looks pretty empty in general. Should we be also registering all the `Msg` types as implementations of the `*sdk.Msg` interface with the normal `codec.InterfaceRegistry` ?

This seems to be done through `RegisterMsgServiceDesc` function already, see https://github.com/cosmos/cosmos-sdk/blob/dfe3e7a8d728bbdbe48a7ad8f95e8dbbda01d610/types/msgservice/msg_service.go#L15, I'm not sure why we kept registering twice in the cosmos-sdk modules but that's something that works because it's accepted by the current implementation of the interface registry: https://github.com/cosmos/cosmos-sdk/blob/master/codec/types/interface_registry.go#L145-L148

**Comment by frumioj** [comment]
> > Also, I'm noticing that [x/ecocredit/codec.go](https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/codec.go) looks pretty empty in general. Should we be also registering all the `Msg` types as implementations of the `*sdk.Msg` interface with the normal `codec.InterfaceRegistry` ?
> 
> This seems to be done through `RegisterMsgServiceDesc` function already, see https://github.com/cosmos/cosmos-sdk/blob/dfe3e7a8d728bbdbe48a7ad8f95e8dbbda01d610/types/msgservice/msg_service.go#L15, I'm not sure why we kept registering msg implementations twice in the cosmos-sdk modules but that just works because it's accepted by the current implementation of the interface registry: https://github.com/cosmos/cosmos-sdk/blob/master/codec/types/interface_registry.go#L145-L148

Noting also: https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/module/module.go which calls `RegisterMsgServiceDesc`. I don't understand what the canonical way of registering types is for Cosmos. It seems to be done in a different way by each module, and can be done in multiple different ways by the caller. It would be nice if there was some standardization among these mechanisms, and only one way provided to the caller.

**Comment by blushi** [comment]
> Noting also: https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/module/module.go which calls `RegisterMsgServiceDesc`. I don't understand what the canonical way of registering types is for Cosmos. It seems to be done in a different way by each module, and can be done in multiple different ways by the caller. It would be nice if there was some standardization among these mechanisms, and only one way provided to the caller.

Where do you see `RegisterMsgServiceDesc` in https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/module/module.go? Or do you mean it's called through `module.RegisterInterfaces`? That's the way it's supposed to work, when starting a new app and registering modules with the module manager, we loop through the modules `RegisterInterfaces`.

**Comment by frumioj** [comment]
> > Noting also: https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/module/module.go which calls `RegisterMsgServiceDesc`. I don't understand what the canonical way of registering types is for Cosmos. It seems to be done in a different way by each module, and can be done in multiple different ways by the caller. It would be nice if there was some standardization among these mechanisms, and only one way provided to the caller.
> 
> Where do you see `RegisterMsgServiceDesc` in https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/module/module.go? Or do you mean it's called through `module.RegisterInterfaces`? That's the way it's supposed to work, when starting a new app and registering modules with the module manager, we loop through the modules `RegisterInterfaces`.

I saw this:
```
func RegisterTypes(registry codectypes.InterfaceRegistry) {
	msgservice.RegisterMsgServiceDesc(registry, &_Msg_serviceDesc)
}
``` in https://github.com/regen-network/regen-ledger/blob/master/x/ecocredit/codec.go

**Comment by blushi** [comment]
> Maybe nothing, since it is ultimately the same call for `x/group` although more is done in that module's codec:
> 
> https://github.com/regen-network/regen-ledger/blob/master/x/group/codec.go

yeah there is more in group codec for amino-json support, which we're gonna add as well in the ecocredit module.
