### ISSUE TITLE
bug: Output of create group --generate-only gives "null" which is invalid JSON

### ISSUE THREAD

**Issue by frumioj** [regen-network/regen-ledger#473]
## Summary of Bug

```
frumiousj@dirtycomputer regen-ledger regen tx group create-group regen1m0nxnyeq6ywy7hzlrvncytr4c5x5css3mhhxme null onemember.json --chain-id test --fees 5000uregen --keyring-backend test --generate-only
```
Outputs the following JSON:
```
{"body":{"messages":[{"@type":"/regen.group.v1alpha1.MsgCreateGroup","admin":"regen1m0nxnyeq6ywy7hzlrvncytr4c5x5css3mhhxme","members":[{"address":"regen17xpfvakm2amg962yls6f84z3kell8c5l0mguae","weight":"1","metadata":"c29tZSBtZXRhZGF0YQo="}],

```
--> "metadata":"null"}]

```
,"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uregen","amount":"5000"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}
```
frumiousj@dirtycomputer regen-ledger % cat onemember.json
{
	"members": [{
	    "address": "regen17xpfvakm2amg962yls6f84z3kell8c5l0mguae",
		"weight": "1",
		"metadata": "c29tZSBtZXRhZGF0YQo="
	}]
}

## Version

Current commit hash in my branch: 51943fb892a3653a4f76957763501daefb750a6f

## Steps to Reproduce

1. Create a JSON file as shown above (onemember.json)
2. Run the `regen tx group create-group` command as shown above, without supplying group metadata.
3. Inspect the output JSON for `"metadata":"null"` which should be `"metadata":null`
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Closing this as this is no longer an issue in the sdk implementation.
