### ISSUE TITLE
ORM micro Internal API audit

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#490]
Limited to the functions listed in #455 

- [ ] Are state machine related functions and types well-named and organized?
- [ ] Is everything well documented (godoc as well as README.md in module directory)

**Comment by robert-zaremba** [comment]
### First batch

1. the Save method performs an update - asserts that the key is already there and overwrites the value. So the name is a bit missleading IMHO. I suggest to rename it to Update. 

2. `Create` method will always overwrite. I think calling it `Set` is more intuitive (this is the most popular method in KV APIs).
3. `a.Table()` returns a private structure. Returning a private types is a bad API. Instead we should return a public interface if possible.
4. in `uniqueKeysAddFunc` why do we use iterator instead of using `store.Has`? https://github.com/regen-network/regen-ledger/blob/master/orm/indexer.go#L103

**Comment by aaronc** [comment]
@robert-zaremba this duplicates #455 and adds scope. The goal is to minimize scope to what is needed for the eco-credit release. Can we close this and stick with #455?

**Comment by robert-zaremba** [comment]
Let's keep this task, and link it to the #455 (as a subtask) - this will be only the API audit of what's listed there.

**Comment by ruhatch** [comment]
I think I'll implement both `Set` and `Create` so that users can decide if they care about overwriting or not.

**Comment by robert-zaremba** [comment]
With `Set` I would expect that it will work in both cases (record exists and when it doesn't exist).

**Comment by robert-zaremba** [comment]
Thanks for renaming `AfterSaveInterceptor`
