### ISSUE TITLE
Decide & implement final fee mechanism & value for credit class instantiation

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#495]
Related to #383 and #351, we need to come to a final decision for the mainnet parameter value for the fee.

Currently the fee is [10000uregen](https://github.com/regen-network/regen-ledger/pull/375/files#diff-efd960bf117d4a8c1b9ac065b3438c4538735adc0b4eeafd46117120da3fc240R12), but we should either upgrade this to a more sensible default, or override in the upgrade handler for mainnet.

**Comment by clevinson** [comment]
On the product backlog refinement call today we were discussing different options for this and have settled on 20 REGEN as an initial value for this. I'll be following up with a forum post to share the rationale and see if there's any feedback from the larger community as to what this value should be in the on-chain upgrade.

**Comment by ruhatch** [comment]
@clevinson can we make a quick decision about a temporary mechanism and the fee value in the meeting today?

**Comment by ruhatch** [comment]
Decided we'll keep burning for now and we'll set the default value to 20 REGEN (i.e. 2e7uregen)
