### ISSUE TITLE
Update Credit Class Designer to "Credit Class Admin"

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#496]
We had a call with the science team today where we deemed that Credit Class Designer is probably not the right name for what we mean (in x/ecocredit documentation & code).

It's often the case that someone will be "designing" a credit class, but not actually wanting to manage the process of managing a credit class.

Similarly, the AllowList should probably be called an allow list for "Credit Class Creators", as that's the technical capabilities this will have.

**Comment by ryanchristo** [comment]
Ok, I think it makes sense for now to have the creator become the admin.

I was hoping that we could support the assignment of an admin, in which case the creator could be on the approved list and the creator could assign an admin who is not on the approved list, but I realize this would require changes to the proto definitions and the permissioned approach is only meant to be temporary.

I think removing the CLI parameter for `admin` and using `--from` helps make things more clear from a user perspective. The `admin` parameter implies an admin can be assigned and that the creator (sender) and admin are different, which is not the case and which might cause confusion.
