### ISSUE TITLE
Completeness audit, fully implemented with tests

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#509]
Assigned to the QA Team.

- [x] Genesis import and export of all state
- [x] Query services
- [x] CLI methods
- [x] All necessary migration scripts are present (if this is an upgrade of existing module)
- [x] Test grpc-web query and post

**Comment by clevinson** [comment]
@kaustubhkapatral is there a status update on this? Can you mark which checklists items have been completed?
