### ISSUE TITLE
Should we be charging some set gas per loop step in ecocredit msg server?

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#519]
CreateBatch, Send, Retire, and Cancel all require looping to some degree. We should probably charge some extra gas similar to what we do in x/feegrant.

Currently in feegrant & authz we set 10gas per extra loop step. Should we stick with this same number here? Or update based on some new / contextual requirements for ecocredit?

**Comment by ruhatch** [comment]
Group is using 20 gas per-iteration, I guess it doesn't matter too much as long as it's proportional to the size of the loop. 

I'll implement it with 20 gas for now and we can always change that! Let me know what you think.
