### ISSUE TITLE
Add MaxMetadataLength for credit class & credit batch metdata

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#520]
Credit class & credit batches should have a max metadata length (similar to [x/group module](https://github.com/regen-network/regen-ledger/blob/adcf73fe08ee82240b8677a1a0a40cb4427219f1/x/group/spec/03_messages.md#msgcreategroup)).

We should come up with a sensible max metadata limit, and also ensure documentation is updated to communicate that there is a limit to metadata size.

**Comment by clevinson** [comment]
@aaronc suggested 256 bytes as a number that we should use for MaxMetadataLength. I think this makes sense assuming that this field is not storing raw metadata, but rather just content identifiers / hashes / URIs that identify metadata that lives somewhere off chain (or onchain but in the data module).

@aaronc Should we be more explicit about what the structure of that metadata looks like? Should it be a string following a URI format (`[scheme]://[host]/[path]`) ?

**Comment by ruhatch** [comment]
@clevinson do we want this to be implemented as a param? A comment in the group module suggests that that wanted to be migrated to a param later on:
```
// MaxMetadataLength defines the max length of the metadata bytes field
// for various entities within the group module
// TODO: This could be used as params once x/params is upgraded to use protobuf
const MaxMetadataLength = 255
```

**Comment by clevinson** [comment]
I think we should probably hold off implementing as a param for now (similar to group module). In group we suggested doing that once we refactor how x/params works, and that's going to happen on a longer timeline.

**Comment by technicallyty** [comment]
should we also charge gas based on the length of the metadata? in ethereum storing a 256-bit word costs around 20,000 gas. for our case i dont think it needs to be that high - but imo should have some sort of storage cost
