### ISSUE TITLE
Update SDK fork (with perm vesting acc) to v0.44

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#521]
We need to upgrade out fork of cosmos-sdk to v0.44, and then update the go.mod here accordingly.

**Comment by amaurym** [comment]
Some more details on this (cc @likhita-809).

Currently, regen-ledger uses our own `regen-network/cosmos-sdk@v0.43.0-regen-1` fork of the SDK (it adds permanent vesting accounts).

https://github.com/regen-network/regen-ledger/blob/c179d8abb38ad7f6f347ab3f96670d2d0d4dc4ed/go.mod#L28

## Proposal

1. Update our fork to 0.44 in https://regen-network/cosmos-sdk
    - [ ] create a new branch `v0.44.x-patches` off of `release/v0.44.x`
    - [ ] create a PR targetting `v0.44.x-patches`, with one commit which is cherry-picking https://github.com/regen-network/cosmos-sdk/commit/30db931423ceb19ca2a71f47e76fd4e8c4f451e7
    - [ ] merge the PR (should be fast, logic is already reviewed)
    - [ ] create the `v0.44.0-regen-1` tag off `v0.44.x-patches`
2. In this repo, update go.mod to use `v0.44.x-patches`

@clevinson does that lgty?
