### ISSUE TITLE
ORM Improvements (x/group)

### ISSUE THREAD

**Issue by ruhatch** [regen-network/regen-ledger#529]
We're currently auditing the ORM module for use in `x/ecocredit` in #455, be we're also using it in the `x/group` module. I wanted to track a few issues here that I'd like to see addressed at some point.

- [ ] Move `Index` interface from `orm.go` to `index.go` and improve documentation
- [ ] Move `Iterator` interface from `orm.go` to `iterator.go`
- [ ] Add more `var _ InterfaceName` for indexes and iterators to make clear which types need to implement which interfaces
- [x] Currently genesis import and export requires `PrimaryKey` interface, which means it might not work with `AutoUInt64` tables, can we check this?
- [ ] Rename `primary_key.go` to `primary_key_table.go` and `auto_uint64.go` to `auto_uint64_table.go` to make it clearer they're table implementations
- [ ] Check if the `Persistent` interface is used at all (I don't think it is) and remove it if unnecessary
- [ ] Move error types into `errors.go`

**Comment by ruhatch** [comment]
This could be broken into a small epic if needed.

@blushi if you have any other things that you've noticed, could you please add them here?

**Comment by ryanchristo** [comment]
It looks like all these items have been addressed in the sdk implementation:

- the `Index` interface has been moved to `ormtable/index.go`
- the `Iterator` interface has been moved to `ormtable/iterator.go`
- `_InterfaceName` has been added for the following
  - `indexKeyInterfaceName`
  - `storeInterfaceName`
  - `messageTableInterfaceName`
  - `messageReaderInterfaceName`
- `primary_key.go` has been moved to `ormtables/primary_key.go`
- `auto_uint64.go` has been moved and renamed to `ormtables/auto_increment.go`
- `Persistent` interface has been removed
- Error types have been moved to `types/ormerrors/errors.go`
