### ISSUE TITLE
Should ecocredit's EventReceive differentiate between retired amounts and tradable amounts?

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#531]
## Summary

ecocredit currently sums tradable and retired credits and feeds that sum into EventReceive for the messages CreateBatch and Send. Subscribers of this event won't be able to tell the specific amounts for retired/tradable credits.

## Problem Definition
This could pose an issue for use cases where a service may be listening to those events and wanting to differentiate amounts. 

Both these messages do, however, call the retire function which emits a Retired event that specifies a retired amount, so a service _could_ just subtract from that event to get the tradable amount. This could be a bit of a nuisance though. 

## Proposal

Change the event to differentiate between retired and tradable amounts. 

```diff
// EventReceive is an event emitted when credits are received either upon
// creation of a new batch or upon transfer. Each batch_denom created or
// transferred will result in a separate EventReceive for easy indexing.
message EventReceive {
  // sender is the sender of the credits in the case that this event is the
  // result of a transfer. It will not be set when credits are received at
  // initial issuance.
  string sender = 1;

  // recipient is the recipient of the credits
  string recipient = 2;

  // batch_denom is the unique ID of credit batch.
  string batch_denom = 3;

-  // amount is the decimal number of both tradable and retired credits received.
-  string amount = 4;

+  // retiredAmount is the decimal number of the retired credits received.
+ string retiredAmount = 4;

+ // tradableAmount is the decimal number of the tradable credits received.
+ string tradableAmount = 5;
}
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clevinson** [comment]
Sounds like a good improvement to me
