### ISSUE TITLE
JSON validation for "create-batch"

### ISSUE THREAD

**Issue by kaustubhkapatral** [regen-network/regen-ledger#534]
## Summary of Bug

If a json file is generated by a user for just one issuer and multiple `recipient` addresses are added into 1 issuance only the last addresses is credited with the `tradeable` and `retired` amount.

## Version

`master`

## Steps to Reproduce

If a batch is created with a json file which is similar to the following one :-
```
{
    "class_id": "C01",
    "issuance": [
        {
            "recipient": "regen1r9pl9gvr56kmclgkpjg3ynh4rm5am66f2a6y38",
            "recipient": "regen12pm7jqx609tm5ex7za23m8ly8nnd4yyanaqjz0",
            "recipient": "regen1r9pl9gvr56kmclgkpjg3ynh4rm5am66f2a6678",
            "recipient": "regen12pm7jqx609tdf4x7za23m8ly8nnd44yanaqjz0",
            "tradable_amount": "1000",
            "retired_amount": "5",
            "retirement_location": "ST-UVW XY Z12"
        }
    ],
    "metadata": "Y2FyYm9uCg==",
    "start_date": "2021-09-08T00:00:00Z",
    "end_date": "2022-09-08T00:00:00Z",
    "project_location": "AB-CDE FG1 345"
}
``` 
It will only credit the last address in the list ie. `regen12pm7jqx609tdf4x7za23m8ly8nnd44yanaqjz0`

It would be better to have validation for number of recipient address based on number of issuances in the array and reject the transaction.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clevinson** [comment]
Nice catch! Tagging as a nice-to-have as this is not state machine breaking and could also come in a patch release to v2.0 after we upgrade.
