### ISSUE TITLE
Add support for updating a credit class

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#535]
Currently we don't actually have implemented a msg for updating a credit class (by CreditClassAdmin).

We discussed this when changing the creator's name from `CreditClassDesigner` to `CreditClassAdmin`, and also noticed that its actually [in the RFC](https://github.com/regen-network/regen-ledger/blob/master/rfcs/001-ecosystem-service-credit-module.md#update-credit-class).

Unless there was a specific reason we decided to exclude it from Regen Ledger v2.0, I think it would be valuable to add in and include in this release. In particular, I think it would be very useful for credit class admins to be able to update issuer lists as those may change over time.

## Proposal

```proto

// MsgUpdateClassAdmin is the Msg/UpdateClassAdmin request type.
message MsgUpdateClassAdmin {

  // admin is the address of the account that is the admin of the credit class.
  string admin = 1;

  // class_id is the unique ID of the credit class.
  string class_id = 2;

  // new_admin is the address of the new admin of the credit class.
  string new_admin = 3;
}

// MsgUpdateClassIssuers is the Msg/UpdateClassIssuers request type.
message MsgUpdateClassIssuers {

  // admin is the address of the account that is the admin of the credit class.
  string admin = 1;

  // class_id is the unique ID of the credit class.
  string class_id = 2;

  // issuers are the updated account addresses of the approved issuers.
  repeated string issuers = 3;
}

// MsgUpdateClassMetadata is the Msg/UpdateClassMetadata request type.
message MsgUpdateClassMetadata {

  // admin is the address of the account that is the admin of the credit class.
  string admin = 1;

  // class_id is the unique ID of the credit class.
  string class_id = 2;

  // metadata is the updated arbitrary metadata to be attached to the credit class.
  bytes metadata = 3;
}
```

**Comment by aaronc** [comment]
Yeah, I just didn't make time for adding these in my initial MVP
