### ISSUE TITLE
Note to Validators

### ISSUE THREAD

**Issue by faddat** [regen-network/regen-ledger#569]
Hi,

I'm operating a relayer. If you are operating a validator, it is very important that you:

```
systemctl enable systemd-timesyncd
systemctl start systemd-timesyncd
```

please.

If you do not, there are time drift errors, and well, the Hermes default of five seconds is really pretty generous. We should be less than five seconds apart.

**Comment by ryanchristo** [comment]
Closing provided https://github.com/cosmos/gaia/issues/1018#issuecomment-991775795
