### ISSUE TITLE
Off-chain Resolver API

### ISSUE THREAD

**Issue by dtkong** [regen-network/regen-ledger#572]
Define an API for off-chain resolvers that will store data referenced by the data module.

**Comment by robert-zaremba** [comment]
Is this task to query the on chain data or to use on chain IDs to easily pack and query remote servers? (the title suggest the latter, but the comments suggest the former).

**Comment by aaronc** [comment]
> Is this task to query the on chain data or to use on chain IDs to easily pack and query remote servers? (the title suggest the latter, but the comments suggest the former).

It's to have a standardized spec for on-chain hashes that will be queried on off-chain servers. The chain contains the hashes and clients will use that to query remote servers basically.
