### ISSUE TITLE
Cross-Chain Bridges

### ISSUE THREAD

**Issue by dtkong** [regen-network/regen-ledger#573]
All things bridges:

Regen Network has a need for ecocredits (and REGEN token) to be bridged to other chain ecosystems due to a desire for interoperability (building new use cases) as well as the fragmentation of demand/users &app devs.  

The ecosystems that are important as follows.

* Cosmos IBC
* Polygon (in particular, KlimaDAO)
* Celo
* Ethereum

Cosmos IBC is low-hanging fruit, and we should get easily as IBC becomes more mature. 

Much of the demand still lies in Ethereum ecosystems of which Polygon is a layer 2. KlimaDAO is expected to be a demand partner for Regen's credit supply pipeline that we need to tap into.

This epic is about exploring options and tradeoffs for different implementations on different networks. There's considerations of UX, speed, security, trust models, etc.

**Comment by robert-zaremba** [comment]
### Using IBC 

Implementing IBC method for a new type is not trivial. Currently IBC is implemented for `x/bank` and there is early work started for the new `x/nft` module.

We were discussing with @aaronc (few months ago) a general issue of registering assets and compatibility with IBC. A general recommendation is to use `x/bank` for all assets balance sheet, and use modules for providing additional logic. For permissioned control we could use hooks.

So, I think the best way for supporting IBC will be to rework the `x/ecocredit` to use `x/bank`.

**Comment by robert-zaremba** [comment]
### Celo

There is IBC implementation, still work in progress. Once it will be ready we can use it as any other IBC transfer.

**Comment by robert-zaremba** [comment]
Shall we close this issue? It seams like a discussion would be more appropriate.

**Comment by ryanchristo** [comment]
Closing this epic given the bridge functionality has been added to the ecocredit module and included in Regen Ledger v4.0. A new epic will be created to track a set of new features for the next iteration of bridge functionality, which would include any updates we need to make to support an integration with Axelar.
