### ISSUE TITLE
Technical analysis for cross-chain bridges

### ISSUE THREAD

**Issue by dtkong** [regen-network/regen-ledger#574]

**Comment by dtkong** [comment]
@robert-zaremba is taking the lead on this. It seems? We probably don't need to do much more here as we have the self-custody solution

**Comment by clevinson** [comment]
@dtkong can we close this? It seems out of Lisbon, and in December's product call we had a pretty clear bridge strategy.  Let us know if you think there's still outstanding analysis work to do.

**Comment by robert-zaremba** [comment]
The path we are leaning into is:
1. use self custody bridge until gravity will have more stability and feature completeness (now, the bridge only works Ethereum -> Cosmos side) or bigger need will emerge
2. We were looking at Chainlink solutions (https://chainlinktoday.com/chainlink-2-0-architects-the-future-of-hybrid-smart-contracts/) which give a good perspective. It's not fully decentralized (it's proof of authority, with centrally managed list of validators). It's an improvement against self custody and what's important it enables automation. However they don't support Cosmos Chains yet.
3. Long term we are leaning into Gravity Bridge integration.

**Comment by robert-zaremba** [comment]
Other solutions we were analyzing: Octopus, Optics.

**Comment by ryanchristo** [comment]
Reopening this issue as @robert-zaremba has been leading the analysis of a trustless bridging solution in relation to our current desire to bring assets over from Polygon.

It looks like Axelar Bridge has a currently functioning Polygon <> Cosmos bridge but we may want to consider others and either do a comparison and/or start specking out our needs to make a trustless bridge happen.
