### ISSUE TITLE
Bump Cosmos SDK fork to base off v0.44.2

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#575]
Now that SDK v0.44.2 has been released, we should:
- [x] bump our fork (with perm vesting account) to be based off of this more recent version of the SDK
- [x] bump the dependency in regen ledger's go.mod
- [x] #584
- [x] tag `v2.0.0-rc2` for regen ledger

**Comment by robert-zaremba** [comment]
All subtasks solved and v2.0.0-RC is released!
