### ISSUE TITLE
Add Cosmwasm support in regen ledger, enable in experimental-mode

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#578]
## Summary

Now that cosmwasm has reached 1.0, it'd be great to have it live on Hambach testnet so users can start experimenting with smart contracts on Regen Network.

## Problem Definition

There are features that we may want to enable natively on Regen Ledger, but without requiring that development be tied to the Regen Ledger source code, or Regen Network upgrade & release cycle.

Examples of this could be:
- complex escrow accounts for conditionally managing assets
- automatic triggering of ecocredit issuance based on claims submitted and signed via the data module
- higher level abstractions for submitting claims on the data module

## Proposal

Integrate cosmwasm into Regen Ledger and enable it in the experimental appconfig.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
It looks like CosmWasm might open up opportunities to interoperate with Solana based blockchains as well. I have not looked too deeply into it but [Wormhole](https://github.com/certusone/wormhole) is a bridge that uses CosmWasm smart contracts to support a bridge to Terra. Might be worth looking into when the time comes.

**Comment by dtkong** [comment]
I think this is a good idea. Let's move this forward and figure out permissioning later (or not permissioning if that makes more sense from a biz perspective)

**Comment by dtkong** [comment]
Reportedly there's already a permissioned COSMWASM implementation. Not sure where?

**Comment by clevinson** [comment]
Yeah -- this is documented on the [cosmwasm docs](http://docs.cosmwasm.com/tutorials/governance/).

So just to clarify - regardless of the long term permissioned vs permissionless strategy, we should consider this ticket ready to be worked on since this issue is only about adding it to experimental config for the upcoming hambach release.
