### ISSUE TITLE
Acceptance tests for permanent Locked vesting accounts

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#579]
The following is a set of acceptance tests for permanent locked vesting accounts, which were added in https://github.com/regen-network/cosmos-sdk/pull/42 and should be available via the following CLI command on regen ledger:

```
regen tx vesting create-permanent-locked-account
```

## Creation of Permanent Locked Account

 - [x] If a user tries to create a permanent locked account with a unused address and a fixed amount of REGEN, the transaction succeeds and the vesting account is created.

   GIVEN - target address is an unused address (does not exist in blockchain state)
   WHEN - user tries to create a permanent locked account with a fixed amount of funds for this address
   THEN - transaction is successful, permanent locked account is created

 - [x] If a user tries to create a permanent locked account with an already used address and a fixed amount of REGEN, the transaction fails and the vesting account is NOT created.

   GIVEN - target address is an already used address (exists in blockchain state)
   WHEN - user tries to create a permanent locked account with a fixed amount of funds for this address
   THEN - transaction fails, permanent locked account is NOT created

## Using of Permanent Locked Account

 - [x] If a user with 100 REGEN in a permanent locked account tries to spend 0.001 REGEN, the transaction fails with an insufficient funds error.

   GIVEN - user has 100 REGEN in a permanent locked account
   WHEN - user tries to send 0.001 REGEN to another user
   THEN - transaction fails, insufficient funds error

 - [x] If a user with 100 REGEN in a permanent locked account tries stake 50 REGEN, the transaction succeeds and the tokens are staked.

   GIVEN - user has 100 REGEN in a permanent locked account
   WHEN - user tries to stake 50 REGEN with a validator
   THEN - transaction succeeds, 50 REGEN are staked

 - [x] If a user with originally 100 REGEN from a permanent locked account and a small amount of REGEN additionally from withdrawing staking rewards tries to send the amount of their staking rewards to another user, the transaction succeeds and the tokens are transferred.

   GIVEN - user has 100 REGEN in a permanent locked account, and X REGEN from withdrawing staking rewards
   WHEN - user tries to send X REGEN to another user
   THEN - transaction succeeds, X REGEN are transferred

 - [x] If a user with originally 100 REGEN from a permanent locked account and a small amount of REGEN additionally from withdrawing staking rewards tries to send more than the amount of their staking rewards to another user, the transaction fails and the tokens are NOT transferred.

   GIVEN - user has 100 REGEN in a permanent locked account, and X REGEN from withdrawing staking rewards
   WHEN - user tries to send X+1 REGEN to another user
   THEN - transaction fails, X+1 REGEN are NOT transferred

**Comment by kaustubhkapatral** [comment]
@clevinson Manual testing of acceptance tests for permanent vesting accounts passes successfully for both `v2.0.0-rc1` and `v2.0.0-rc2`
