### ISSUE TITLE
Insufficient error logging for "update-class-admin"

### ISSUE THREAD

**Issue by kaustubhkapatral** [regen-network/regen-ledger#597]
## Summary of Bug

If more than 1 address is passed to `update-class-admin`, it shows an error which just says `invalid address`
```
regen tx ecocredit update-class-admin C01 regen14x0wyl7r0l2clu6hh34kqaulausvjzs0vzed7u,regen1j0wl83ulvwancndjg5jp3r5l2m8jq0fap88ew0
 --from regen1j0wl83ulvwancndjg5jp3r5l2m8jq0fap88ew0 --fees 20uregen --chain-id regen-devnet-6-11 -y

Enter keyring passphrase:
Error: invalid address
Usage:
  regen tx ecocredit update-class-admin [class-id] [admin] [flags]

Flags:

```

## Version

master

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
I think this is ok as is. The CLI help text displays `[admim]` and the example uses a single address.
