### ISSUE TITLE
Follow-ups for buy/sell proto definitions

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#605]
## Summary

Few followups from #560 that were left as open questions.

Some of these points may be left as is, but we should still make sure to have the conversations here or in WG meetings to align on them before releasing full marketplace functionality into the wild.

- [ ] ~Change UpdateBuyOrders api to be more granular ([see comment](https://github.com/regen-network/regen-ledger/pull/560#discussion_r720042033))~ #892
- [x] Add support for explicitly cancelling a sell order ([see comment](https://github.com/regen-network/regen-ledger/pull/560#issuecomment-947079049))
- [x] update `ask_price` field to `repeated Coin`, allowing for a sell order to accept multiple denoms. This may not be a feature we want to enable though, as it creates possibility for strange arbitrage opportunities when exchange rates of "ask denoms" diverge ([see comment](https://github.com/regen-network/regen-ledger/pull/560#issuecomment-947216698))
- [ ] ~Rename `Sell()` & `BuyDirect()` rpc methods to `CreateSellOrders()` and (`CreateBuyOrders()` or `DirectBuy()`)([see comment](https://github.com/regen-network/regen-ledger/pull/560#discussion_r737839878) & [here](https://github.com/regen-network/regen-ledger/pull/560#discussion_r738512313))~

Not explicitly brought up in the review, but two additional pieces on my mind:
- [ ] ~re-evaluate params for `MsgAllowAskDenom` (maybe metadata isn't necessary here if it can be stored in x/bank's `DenomMetadata`?)~
- [x] distinguishing btw `BuyDirect` and `CreateBuyOrder` functionality
  - currently, `BuyDirect` creates a "buy order" that may have some pending state. I'm still not 100% sure of what use case we have for this, and rather think of `CreateBuyOrder` as a separate API call that would actually create a pending order in state, whereas `BuyDirect` would always be against an existing open sell order, and be immediately executable
 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clevinson** [comment]
OK makes sense. @ryanchristo and I started looking into this today...

For now, should the fulfilling of `MsgBuyDirect` calls be done in batch (e.g. in `EndBlocker()`?), or should we be directly fulfilling orders as part of the msg server's implementation of `BuyDirect()` ?

**Comment by aaronc** [comment]
Up to you. Maybe simplest to do it synchronously in the tx

**Comment by clevinson** [comment]
From ledger product call today:
- Add support for explicitly cancelling a sell order (will add this in existing msg server implementation work from @clevinson and @ryanchristo)
- Let's not persist buy orders to state, but store a ORM seq for buy orders so we can auto increment and dispatch events with `buy_order_id`
