### ISSUE TITLE
Handle auto-retire in ecocredit buy/sell functionality

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#621]
- [ ] Add `retirement_location` to `MsgBuy` so that when auto-retire is set to true we know where to retire credits to
- [ ] Update msg server implementation to handle transfer of retired credits

Additionally, in #613 we refactored out a new method for `sendEcocredits` that takes in a `MsgSend_SendCredits` as a parameter. It might make sense to refactor `MsgSend_SendCredits` into its own proto message in `ecocredits/types.proto`, and change its API slightly? Let's evaluate this when we tackle this issue.

**Comment by ryanchristo** [comment]
Unable to add `retirement_location` without resolving #646 first.
