### ISSUE TITLE
Add state sync instructions for bootstrapping validators

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#625]
For mainnet & redwood full-nodes, they will need to use state-sync if they want to avoid having to download multiple binaries in order to bootstrap a full-node from genesis.

This requires a bit of network ops work -- as we'll need to ensure at least 2 nodes are taking state snapshots, and then we should have instructions similar to what's outlined in [this blog post](https://blog.cosmos.network/cosmos-sdk-state-sync-guide-99e4cf43be2f)

**Comment by robert-zaremba** [comment]
I would say we should do:
+ Add a doc page `join-network.md`
+ Write few paragraphs on how to join the network, provide links / RPC addresses both for testnet and mainnet
+ KISS
+ try to not repeat docs from Cosmos SDK - we can link the markdown files instead.
