### ISSUE TITLE
Update data module to use attestation terminology

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#637]
## Summary

During the review process for #236, we discussed the possibility of using attestation terminology in place of data signatures. For example, we would rename `SignData` to `Attest`. Opening this issue for further discussion.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
+1 for attest. 

definitions:
- declare that something exists or is the case.
`"I can attest to his tremendous energy"`
- be a witness to; certify formally.
`"the witnesses must attest and sign the will in the testator's presence"`

Seems more in line with the functions intended purpose
