### ISSUE TITLE
Decide on basket picking semantics

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#640]
regen-network/regen-ledger#610 specified that even if "picking" credits from baskets is generally disabled, users that put credits in the basket can pick those same credits out.

This poses a conundrum because the take functionality randomly chooses credits and so a user may not be able to pick the credits they deposited because another user may have already randomly taken this out.

There are two viable solutions:
1. either no users can pick credits or any user can pick any credits which could be a configurable boolean
2. retain the existing specification but make these modifications to retirement behavior:
  a. when credits are deposited in a basket, they are retired from their batch
  b. the take operation is replaced with retirement and basket tokens are retired directly without distinguishing which batch got retired (because they were already "retired" upon deposit)
  c. when credits are picked from the basket, the original batch credits are "unretired"

(2) definitely introduces some weird semantics around retirement. We could introduce a third state for credits where they are "basket escrowed or transformed", but then we have no way of really knowing when the original batches are actually retired.

The simplest behavior to implement and to reason about is probably (1).

**Comment by dtkong** [comment]
My suggestion is for **1** to let any user pick token. With the caveat, users who pick specific credits would pay a fee to the token pool to do so. 

My reasoning is that 
A. there is prior art for this see below (NFTX)
B. approach 2 seems complicated for unclear benefit (I'm still unsure it makes sense)
C. the use case of basket depositors wanting their original ecocredits back isn't really something basket mechanisms are suited for. that seems more like a collateralized debt position (CDP) model. there's a proposed design for "floor perps" which could work but are substantially more complex https://www.paradigm.xyz/2021/08/floor-perps/
for us, I believe the wise route is to advise depositors that turning a nonfungible or semifungible token into a fungible one does not provide the guarantees of nonfungibility. 

https://docs.nftx.io/tutorials/redeeming
Prior art is from NFTX, a NFT indexing/liquidity protocol which is providing a similar service. How to turn a Cryptopunk NFT -> into a tradeable ERC20. 

For NFTX, one has to pay a 5% fee in the pool's token to redeem a specific NFT. E.G. I trade my Cryptopunk for 1 $PUNK ERC20, but I have to pay 1.05 $PUNK to redeem a specific Cryptopunk in the pool. 

I believe this also the model that Toucan is converging on (or at least I brought it up). 

For our use case, we wouldn't necessarily require the 5% fee in the basket token. It could be paid in $REGEN that might make more sense as a platform-based fee. There are issues with having the fee in the basket token as at the end there will be some amount of underlying credits that will not be redeemable.

**Comment by clevinson** [comment]
@dtkong Where would you imagine these fee funds go to? The basket creator? or to the Regen Network community-spend-pool (which can be utilized via on-chain governance spend proposals)?

**Comment by aaronc** [comment]
#649 addresses this but there is still the question of how the fee is set. Is it a governance operation? Fixed price or percentage? The same for all baskets?

**Comment by clevinson** [comment]
This is all aligned on now, so closing this issue.
