### ISSUE TITLE
Are basket multipliers really needed?

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#641]
In [#610](https://github.com/regen-network/regen-ledger/pull/610/files#diff-4fac056371bff38744204e1a5f828314f25880330750911fe89089319e65c499R498-R516), different "multipliers" could be applied to specific filters in a basket to change how many basket tokens those credits produced.

For example we could have "class A" credits with a multiplier of 1000 and "class B" with a multiplier of 800. So 1.0 class A credit would product 1000 basket tokens whereas 1.0 class B credits would produce 800 basket tokens. (Note that basket tokens are integers where as credits are decimals so we always want some large integer multiplier like 1000 or 1000000.)

The underlying motivation for this is to deal with the fact that some credits may be deemed more or less ecologically useful by curators.

But maybe it's not needed? Removing this would definitely simplify basket design and implementation

**Comment by dtkong** [comment]
I do think it is unnecessary. It's better to keep the credits <-> basket tokens 1:1 IMO. 

Although I understand some of our carbon credits may have different units (not 1 ton?). when Gregory and I discussed, he thought that might be the reasoning for having the multiplier.

**Comment by clevinson** [comment]
@dtkong at this point, all carbon credits on-chain need to be issued in units equivalent to 1ton (with 6 decimal point precision). To have credits tracked in other units would require a different "credit type" being registered on-chain. And I think in the current design, different credit types (e.g. carbon, methanee, biodiversity) cannot be basketted together (as the underlying units are not necessarily interchangeable)

**Comment by aaronc** [comment]
#649 addresses this but one question I have is whether we should allow different exponents for different baskets or if that should be standardized by credit type. i.e. all carbon credit baskets always have 10^6 as the exponent.

**Comment by dtkong** [comment]
> @dtkong at this point, all carbon credits on-chain need to be issued in units equivalent to 1ton (with 6 decimal point precision). To have credits tracked in other units would require a different "credit type" being registered on-chain. And I think in the current design, different credit types (e.g. carbon, methanee, biodiversity) cannot be basketted together (as the underlying units are not necessarily interchangeable)

Ok makes sense. To confirm, the reason why it needs to be 1 ton is because the existing "carbon" credit type `unit` is denominated in tons? (It doesn't "have" to be that way).

Are we enforcing that only the same credit types should be in the same basket?

**Comment by dtkong** [comment]
> Are we enforcing that only the same credit types should be in the same basket?
Re latter question, I see that that's the case in #649

**Comment by clevinson** [comment]
Closing this for now, as we're not including basket multipliers in the initial specification (all basket credits must be of the same credit type at first).
