### ISSUE TITLE
Should metadata fields in projects / credit classes / credit batches be matched with a field for metadata_hash?

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#668]
As we get more usage on ecocredits, it may be worthwhile to entertain adding a `metadata_hash` field alongside `metadata` fields in the project, credit class, and credit batch data models.

Few ways we're handling this use case in similar situations: 
- In NFT module we do this with separate `uri` and `uri_hash` [fields](https://github.com/cosmos/cosmos-sdk/blob/master/proto/cosmos/nft/v1beta1/nft.proto#L22-L26).
- In data module we're in the process of specifying an off-chain resolver API & field for data module hashes

@robert-zaremba proposed this as part of his review for #608, but rather than adding a hash field just to projects, I think we should rather ask this question across the metadata fields for different entities.

**Comment by robert-zaremba** [comment]
ref: https://github.com/cosmos/cosmos-sdk/pull/9747#discussion_r686371143  (we also have it in x/bank).

**Comment by robert-zaremba** [comment]
Moreover if metadata is expected to be an URI, then let's call it `uri` or `metadata_uri`.
