### ISSUE TITLE
App wiring: add ecocredit module to module manager

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#689]
## Summary

Following #671, we need to wire up `BeginBlocker` for the ecocredit module.

As far as I understand, we need to include the ecocredit module when initializing the module manager and then include the module when setting the order for begin blockers. The ecocredit module does not implement the `AppModule` interface and in attempting to do so there is a conflict with `RegisterServices` - we use a custom `Configurator` in the ecocredit module with a different signature.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
we should rename the function defined in the interface here: https://github.com/regen-network/regen-ledger/blob/master/types/module/server/module.go#L11

imo doesn't make much sense to have this method named as such as it collides with the sdk's module interface as you've stated above.

**Comment by aaronc** [comment]
we should just get the app wiring work done with and be done with `AppModule`

**Comment by ryanchristo** [comment]
Looking into adding BeginBlocker to Configurator as possible solution for the time being.
