### ISSUE TITLE
Refactor ecocredit proto files into separate packages

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#695]
Even though the basket and marketplace code is currently in the same module, it would enhance readability to split these pieces out into separate proto packages like `regen.ecocredit.basket.v1`, etc. In the future, they could be refactored into standalone (sub)-modules

**Comment by technicallyty** [comment]
+1

should i update my basket PR with this idea to get this started?

**Comment by aaronc** [comment]
> +1
> 
> should i update my basket PR with this idea to get this started?

if you like... although smaller PRs are a little easier and quicker to get through

**Comment by technicallyty** [comment]
done in https://github.com/regen-network/regen-ledger/pull/709
