### ISSUE TITLE
ESP result CLI query support

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#7]
Given an ESP result ID
When a user types in `xrncli esp query result <result-id>`
Then they should get back the ESP result data

**Comment by fgimenez** [comment]
Is this issue still relevant? If so I'd like to give it a try =)

**Comment by aaronc** [comment]
@fgimenez thanks for reaching out! This is unfortunately likely no longer relevant. You're on our telegram DVD channel right? If you would like to get involved in something else, maybe let's chat on telegram? Appreciate your initiative!

**Comment by clevinson** [comment]
@aaronc should this get closed ?
