### ISSUE TITLE
Add delete method to orm index

### ISSUE THREAD

**Issue by robert-zaremba** [regen-network/regen-ledger#706]
## Summary

Currently, we do few [round-trips](https://github.com/regen-network/regen-ledger/pull/671/files#diff-f5804fb07cce9f805dddda1d5ecbf2cf50a352a5db6275ebb26eee1f4f2fbf52R24) to remove a record based on index:
* querying index
* deserializing index value (row id)
* querying "main table"
* deserializing record
* removing both form the main table and index

All of this can be handled by index

ref: https://github.com/regen-network/regen-ledger/pull/671/files#r788275545

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
x/ecocredit is being migrated to the new ORM ASAP so the current ORM is effectively considered deprecated. If there is any way to improve efficiency with the new ORM, let's addres in the SDK

**Comment by aaronc** [comment]
Indexes in the new ORM do have a delete method: https://github.com/cosmos/cosmos-sdk/blob/master/orm/model/ormtable/index.go#L50. Does this address the issue? We could also add a `Delete` method to iterators too if that would be even better.

**Comment by robert-zaremba** [comment]
The goal is to remove without deserializing on the user side (as referenced in the description).
So  adding it to iterator should bsolve the issue.

**Comment by aaronc** [comment]
It's impossible to delete without deserializing the primary entry. That's needed to know which indexes to delete
