### ISSUE TITLE
Acceptance tests format and execution

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#711]
## Summary

In #633 and #673, there was a request to update the format of acceptance tests (i.e. replace if/then statements with simpler language that summarizes rather than repeats given-when-then statements). There was also a question of whether we could leverage tools to make the acceptance tests executable (e.g. using something like https://github.com/cucumber/godog). Let's further discuss. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by aaronc** [comment]
One issue I've encountered with godog is that there isn't support for `testing.T` so it's impossible to use `gomock`, unless someone adds support (https://github.com/cucumber/godog/issues/100).

We could consider doing this ourselves and adding support. I have some ideas on how.

There is also [go-bdd](https://github.com/go-bdd/gobdd) which supports a `testing.T` interface and could be used with gomock.

I would suggest doing a spike with go-bdd and some tests for ecocredits core or baskets to see how we feel about the library. I'll see if I can find a bit of time to play with this. Is anyone else possibly interested? @ryanchristo @technicallyty @robert-zaremba ?

**Comment by aaronc** [comment]
I would also note that we should probably expect to make some upstream contributions to whichever cucumber library we choose. I'm fine with that. But we should choose the one that seems to have the best engineering foundations

**Comment by aaronc** [comment]
Spent a few minutes trying out gobdd in #832.

A few reflections:
* overall not too bad, not too much overhead compared to the previous test for this case `TestTakeMustRetire`
* no templates for undefined steps nor pending state like godog: https://github.com/cucumber/godog#step-4---create-godog-step-definitions
* no cucumber-like output in execution like godog
* I wish I didn't need to pass `StepTest` and `Context` to every method (only when I need it) OR there were templates like godog

So overall this approach works, integrates with gomock and assertion libraries easily. And could use some dev UX work for sure

**Comment by aaronc** [comment]
Created https://github.com/aaronc/gocuke to address all these issues

We should probably move to the regen or cosmos org. Also happy to pick a better name!

**Comment by ryanchristo** [comment]
This is looking great. Very lightweight and great documentation. I see you've updated your draft pr with a basket example too. Do you feel it is ready to start migrating existing tests over? Do you see this as something we should prioritize for v4.0 or maybe just start using when writing new tests?

**Comment by aaronc** [comment]
A few other thoughts on my mind:
* we could reuse the same `.feature` files for both unit and integration tests in separate test files - so unit tests would use a very lightweight setup with mocks, integration tests would use a full network setup - but possibly the same acceptance test scenarios could be applied to both
* how about integration tests that can either use the in process test network _or_ a live testnet. This could be done with environment variables - i.e. if there is an RPC URL + some test keys defined, then don't spin up an in-process network but target the testnet. We could maybe forego a lot of manually testing with this approach

**Comment by aaronc** [comment]
> Do you feel it is ready to start migrating existing tests over?

I now consider it ready after making some API updates which I think make it even simpler and tagged as v0.5.0: https://pkg.go.dev/github.com/aaronc/gocuke. Would be happy to tag this API as v1.0 after we move to regen-network and let a few people do some testing and see if they encounter any issues.

**Comment by ryanchristo** [comment]
Opened the following issues to address individual components:

- [ ] #893
- [ ] #894
- [ ] #895
- [ ] #896

**Comment by ryanchristo** [comment]
I think this issue is safe to close now that we've agreed upon a format and we can address any additional needs in the review process with the issues listed above.
