### ISSUE TITLE
Upgrade to cosmos-sdk 0.38

### ISSUE THREAD

**Issue by ethanfrey** [regen-network/regen-ledger#74]
Code is getting old... let's update dependencies and re-do all modules to a clean 0.38 (Which should be released Jan 10th?)

This let us then easily update to cosmos-sdk release with support for upgrades https://github.com/cosmos/cosmos-sdk/pull/4233 (and key management https://github.com/cosmos/cosmos-sdk/pull/4616). And keep in sync again.

Big changes in module structure is here: https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md

**Comment by ethanfrey** [comment]
@aaronc I think 0.38 should be tagged in the next day or two, including upgrades.
This is a great time ot start an overhaul of regen-ledger to make it modern, and prepare for the next incentivized testnet.

I would like to prepare this task so we have more well defined work in the dev backlog.
What is missing is determining which existing modules we want to bring forward and documenting them. If a module (like x/geo) will be needed but we have no clear spec, we should just omit it for now, we can always port them one at a time (from the v0.5 tag).

Personally, I would make this a clean gaia with the basic regen changes (token, binary names, env and bech32 prefixes, etc). Then add the upgrade module, and the various key management features as they are integrated into cosmos sdk (with 0.39) - fee_delegation, msg_authorization, and groups. If some of those modules end up in eg. cosmos/modules and not in the cosmos-sdk we can pull them in without waiting for a tagged cosmos-sdk release.

I think many old modules are either now included in the key management work (in a much more complete format), or are just specs. The remaining ones mostly need heavy thinking on them, so I would actually propose a bare-bones `xrnd` for this issue. We may add eg. tokens in another issue, as I know you have spent some time spec-ing that out and it doesn't seem there is so much uncertainty. geo-spatial and rdf data sources definitely need serious architecture time upfront before they are spec'd and ready to develop.

**Comment by aaronc** [comment]
I agree we should start with bare-bones. The question is whether to do right at 0.38 or wait until protobuf is further along. I think likely we want to wait until the protobuf stuff starts getting merged into master which I think is not far off.

I agree the geospatial and RDF stuff needs more upfront design work.

**Comment by clevinson** [comment]
Seems like for the next testnet we will jsut use wasmd, and we will wait til 0.39 to upgrade regen-ledger. @aaronc should we close this?

**Comment by aaronc** [comment]
I agree with that plan. Let's close this and address when 0.39 is ready or close to ready.
