### ISSUE TITLE
Ensure backwards compatibility of tendermint block format

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-ledger#79]
Tracking issue for https://github.com/tendermint/tendermint/issues/4078.

**Comment by aaronc** [comment]
@ethanfrey FYI about the issue above which I'm adding to the upgrades epic.

**Comment by ethanfrey** [comment]
Yes, it is a very important issue.
I think adding a version field would also be nice, but likely a destructive change.
Maybe we can try to get this into tendermint v0.33 and say from then on, there is a backwards compatibility guarantee

**Comment by melekes** [comment]
Sound good to me 👍

**Comment by aaronc** [comment]
Resolved upstream
