### ISSUE TITLE
Add query message for basket class

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#793]
## Summary

Currently we only provide queries for `Basket` and `BasketBalance`. There is no query for `BasketClass` and therefore no way to query for which classes are allowed within a basket.

## Problem Definition

We need to be able to query the allowed credit classes within a basket.

## Proposal

Add query message for `BasketClass` and implement in query server and CLI.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
maybe we could just include the allowed classes in the `Basket` query? wdyt?
