### ISSUE TITLE
Consider consolidating `SellOrdersBy<Attribute>` into one `SellOrders` query

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#909]
## Summary

currently the marketplace proto files specify 2 specific sub queries under `SellOrders`:

```proto
  // SellOrdersByDenom queries a paginated list of all sell orders of a specific ecocredit denom
  rpc SellOrdersByBatchDenom(QuerySellOrdersByBatchDenomRequest) returns (QuerySellOrdersByBatchDenomResponse) {
    option (google.api.http).get = "/regen/ecocredit/marketplace/v1/sell-orders/batch-denom/{batch_denom}";
  }

  // SellOrdersByAddress queries a paginated list of all sell orders from a specific address
  rpc SellOrdersByAddress(QuerySellOrdersByAddressRequest) returns (QuerySellOrdersByAddressResponse) {
    option (google.api.http).get = "/regen/ecocredit/marketplace/v1/sell-orders/address/{address}";
  }
```

however, this could be done under one single `SellOrders` query with the additional fields, and the addition of a `seller,batch_id` index. 

This would also allow more expressive REST queries via query strings (i.e `/marketplace/v1/sellorders?address=regen1,batchDenom?="foo"`), on top of allowing more refined query control (with this we could query for all sell orders under a specific addr AND batch denom).

## Proposal

- add `address` and `batch_denom` fields to `QuerySellOrders` and a `seller,batch_id` index to SellOrder table.
- remove `SellOrdersByAddress` and `SellOrdersByBatchDenom` queries 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
I like the idea but I think this goes again protobuf best practices, which is to keep messages separate as much as possible to avoid unnecessary breaking changes. I think the format we have aligns with best practices but I might be misunderstanding and would be curious to hear what others think.

**Comment by robert-zaremba** [comment]
I think it's fine. It requires an extra index though. Hopefully in 1 year we will offload it.
On the other hand I don't imagine a single user having hundreds of orders. And if it will go into that direction we can always add more granular queries if needed.

> keep messages separate as much as possible to avoid unnecessary breaking changes.

There is always some tradeoff.

**Comment by ryanchristo** [comment]
Product Call Notes:

- awaiting further feedback from interface team

**Comment by ryanchristo** [comment]
We should take into consideration the use of GraphQL (#930) before making any decisions here.

**Comment by ryanchristo** [comment]
I think this is safe to close. We decided to keep separate queries here to limit the number of potential breaking changes in the future and to maintain consistency with other queries in the ecocredit and data module. We can re-evaluate if and when we decide to update our query service to leverage GraphQL (#930).
