### ISSUE TITLE
Implement dynamic batch minting functionality

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#973]
## Summary

As a followup to #924, we need to implement the dynamic batch minting functionality.

- [x] #990

Add message server implementations:

- [x] `MintBatchCredits` #1059
- [x] `SealBatch` #1060

Nice to have:

- ~[ ] `mint-batch-credits` command~
- ~[ ] `seal-batch` command~

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clevinson** [comment]
@robert-zaremba can we transition this off of you to someone else on ledger team? I think its probably best that your focus is exclusively on the other components of the bridge work (e.g. microservice + smart contracts), as those are pieces that I think it would be harder for others to pick up.

**Comment by ryanchristo** [comment]
Closing. The only remaining items are the CLI commands but after speaking about this with @clevinson last week, we don't want to encourage users to set batches to open or use dynamic batch minting.
