### ISSUE TITLE
update `MsgBuy_Order_Selection` to support amino signing

### ISSUE THREAD

**Issue by aleem1314** [regen-network/regen-ledger#989]
## Summary

Using oneof in `MsgBuy_Order_Selection` will break amino signing. We need to update `MsgBuy_Order_Selection` to support amino signing.

## Problem Definition

Using oneof in `MsgBuy_Order_Selection` will break amino signing.

## Proposal

Split them into separate fields (like https://github.com/regen-network/regen-ledger/pull/790).

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
This will be resolved with #905 and #967.
